java-native-access/jna

build.xml

Hi Timothy,
as discussed on the user forum, a patch that will ensure the JNA package can be installed in an OSGi container running on Windows 8.1. There are 2 options to consider:
On the proposed path, we could make the additional native library entry also version specific by adding `...;osname=win;osversion=6.3.0` to make sure that entry only matches on windows 8.1, but that would break as soon as Windows decides to bump that number and there is no wildcard support in Apache Felix as far as I can see to specify something like `6.*.*`. So this is more a FYI than a workable option I guess.
The other alternative would be to add a `*` at the very end to effectively bypass the OSGi container check, but I can see from comments in the build.xml file that it should specifically fail on platforms …

Added OSGi Bundle-NativeCode entry to support Windows 8.1

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32UtilTest.java

Added:
- Encrypt, decrypt, encryption status, and encryption disable:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365005(v=vs.85).aspx
- EFS encrypted files raw backup:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363783%28v=vs.85%29.aspx

Added encryption, decryption and raw backup functions to Advapi32

---

CHANGES.md
src/com/sun/jna/Structure.java
test/com/sun/jna/StructureTest.java

Issue #413: Structure leaves always one element in ThreadLocal set

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/X11.java

Simply added mappings for those 2 functions.
Documentation taken from http://tronche.com/gui/x/xlib/input/XGrabKeyboard.html and Xlib.h.

Added mappings for XGrabKeyboard and XUngrabKeyboard

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Wincon.java
contrib/platform/test/com/sun/jna/platform/win32/WinconTest.java

Actually needed only _GetConsoleDisplayMode_ and _SetConsoleMode_, but thought it worthwhile to contribute some more definitions - at least the simplest ones that do not involve extra structures.

Added some Wincon.h related functions and definitions

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/AbstractPlatformTestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/AbstractWin32TestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/NamedPipeTest.java
contrib/platform/test/com/sun/jna/platform/win32/WinconTest.java

To do that I also added the following improvements:
* Added definition of [FlushFileBuffers](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439(v=vs.85).aspx)
* Added _AbstractPlatformTestSupport_ along with an ability to retrieve the current test name
* Added _AbstractWin32TestSupport_ and moved _assertCallSucceeded_ there since it is so typical of many calls.

Added named pipe API support

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Added missing 'SetLocalTime' + updated the tests to take into account user privileges (stay tuned for the _CHANGES.md_ commit...)

Added SetLocalTime definition to 'com.sun.jna.platform.win32.Kernel32'

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32ConsoleTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32EnvironmentVarsTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32NamedPipeTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Including code to parse the resulting _Pointer_ in _Kernel32Utils_ (wait a moment for the _CHANGES.md_ - the chicken and egg issue...)

Added GetEnvironmentStrings to 'com.sun.jna.platform.win32.Kernel32'

---

www/MacDevelopmentEnvironment.md

When I tried to build JNA on my Mac I also had to install gettext. Before doing so, I would see the error `[exec] configure: WARNING: unrecognized options: --enable-static, --disable-shared, --with-pic` (which is already in the document describing how to build on Mac OS).

Add gettext as a requirement for the Mac build notes.

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/AccCtrl.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32UtilTest.java

Implementation of the aforementioned functions, as well as a few convenient helpers and wrappers. Also modified the internal private fields of SECURITY_DESCRIPTOR_RELATIVE to make getting the Owner, Group and SACL as easy as the DACL.
Also modified the PSID to get the string representation in an easy way.

Added to Advapi32: SetThreadToken, GetNamedSecurityInfo, SetNamedSecurityInfo, GetSecurityDescriptorLength, IsValidAcl, IsValidSecurityDescriptor

---

CHANGES.md
src/com/sun/jna/NativeLibrary.java
test/com/sun/jna/NativeLibraryTest.java

If an Exception/UnsatisfiedLinkError is thrown during the Native.open() call on a library file that has been extracted from the resource path, the extracted library file is not immediately cleaned up: the files only disappear once the using application shuts down, thanks to the deleteOnExit() called upon them in Native.extractFromResourcePath(). However, if the using application keeps (unsuccessfully) retrying to call Native.loadLibrary(), this can fill up the temporary JNA directory rather quickly.
This little change should counteract this scenario.

Cleanup of temporarily extracted files in case of errors

---

.travis.yml

Pass the return value of the ant test to travis

fixed #464

---

CHANGES.md
native/dispatch.c
src/com/sun/jna/Native.java
src/com/sun/jna/Structure.java
test/com/sun/jna/DirectTypeMapperTest.java
test/com/sun/jna/TypeMapperTest.java

When using a type mapper with a direct-mapped library, several problems are exposed.
* Type mapper not found because library options are cached _after_ method resolution (which methods depend on the type mapper option)
* Incorrect error message "Unsupported Structure field"
* Enums not properly converted from integer values on return
* Java return type not properly looked up when a type mapper is in use (the native FFIType is always used)
Adds tests for type mapping of enums for both interface and direct-mapped libraries.

[467] direct enum type mapping

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Pdh.java
contrib/platform/src/com/sun/jna/platform/win32/PdhMsg.java
contrib/platform/src/com/sun/jna/platform/win32/WinPerf.java
contrib/platform/test/com/sun/jna/platform/win32/AbstractWin32TestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/PdhTest.java

Added some (not all) of the API(s) in the _pdh.dll_ - enough to enable using *raw* performance counters - as can be clearly demonstrated from the test.

Added basic Pdh API implementation

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/AbstractWin32TestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32VolumeManagementFunctionsTest.java
src/com/sun/jna/Native.java
test/com/sun/jna/NativeTest.java

- Added (almost) all the functions under [Volume Management Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365730(v=vs.85).aspx) including tests - except for the functions that might affect the host running the test (e.g., _SetVolumeLabel_)
- Improved efficiency of _Native#toString(...)_ to avoid creation of extra strings by pre-detecting the NULL terminator position
- Added _Native#toStringList()_ since it is very common to find double-null terminated string buffers. I used it also in _Kernel32Util#getLogicalDrives_ and changed its return type from and array to a list accordingly.

Added volume management functions

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java
contrib/platform/test/com/sun/jna/platform/win32/AbstractWin32TestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/GDI32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32DiskManagementFunctionsTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32NamedPipeTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java
contrib/w32keyhook/com/sun/jna/contrib/demo/KeyHook.java

- Added duplicate method detection tests for Kernel32, Advapi32 and User32 as they contain most of the low-level API(s) (welcome to add more...) - this is how the issues were discovered and fixed
Kernel32:
- Removed duplicate GetDiskFreeSpaceEx - preserved the one with LARGE_INTEGER definition as it matches the API definition
- Added GetDiskFreeSpace API
- Removed duplicate ReadFile - left and modified the remaining one to use _byte[]_ argument in order to match the WriteFile definition
- Removed duplicate FormatMessage - kept the one with _PointerByReference_ since it is the definition that closest matches the API (+ it is the only one used in the current code)
User32:
- Removed duplicate SetWindowLong - kept the one with the _int_(s) as it matches the API definition
- Removed duplicate …

Found and fixed duplicate method definitions for the same API

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/User32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/src/com/sun/jna/platform/win32/WinUser.java
contrib/platform/test/com/sun/jna/platform/win32/User32UtilTest.java

A good example as to how to pass an array of structures to an API

Added GetRawInputDeviceList definition and utility to User32 interface

---

contrib/platform/src/com/sun/jna/platform/win32/Variant.java
contrib/platform/test/com/sun/jna/platform/win32/VariantTest.java

Propose support for BYTE and CHAR type of VARIANT.

Add support for BYTE and CHAR to VARIANT

---

CHANGES.md
src/com/sun/jna/Structure.java
test/com/sun/jna/ArgumentsMarshalTest.java
test/com/sun/jna/CallbacksTest.java
test/com/sun/jna/StructureTest.java

Fixes issue #475 
Provide a dedicated Structure method to compare native memory between two instances.  Otherwise `.equals()` just compares native pointer and type.

[475] Avoid touching native memory from Structure.hashCode/equals

---

native/Makefile
native/libffi/src/x86/ffi.c
native/libffi/src/x86/ffitarget.h
native/libffi/src/x86/win64.S
test/com/sun/jna/win32/W32StdCallTest.java
www/WindowsDevelopmentEnvironment.md

Rebuilt from scratch and an (almost) bare windows installation.
`libffi` required some tweaks, and more structure by value bugs have been exposed (likely introduced with more recent libffi changes, which will be addressed in a separate PR).

Fix windows builds under MSVC, 32- and 64-bit

---

CHANGES.md
native/callback.c
native/dispatch.c
native/dispatch.h
native/testlib.c
src/com/sun/jna/CallbackReference.java
src/com/sun/jna/Function.java
src/com/sun/jna/Native.java
src/com/sun/jna/NativeMapped.java
src/com/sun/jna/NativeString.java
src/com/sun/jna/ToNativeConverter.java
test/com/sun/jna/CallbacksTest.java
test/com/sun/jna/DirectCallbacksTest.java
test/com/sun/jna/DirectTypeMapperTest.java
test/com/sun/jna/TypeMapperTest.java
www/DirectMapping.md

When using a `TypeMapper` which indicates `String` or `WString` as the native type, final conversion from those types to a native `const char*` or `const wchar_t*` was not being performed, typically passing garbage to the native function.

[496] Handle TypeMapper-returned String/WString in direct mode

---

build.xml
native/dispatch.c
src/com/sun/jna/Native.java
src/com/sun/jna/Structure.java
test/com/sun/jna/JNALoadTest.java

Expects to have class finalizer called in order to perform pre-unload cleanup.
Not safe to call back to JVM in `JNI_OnUnload()` (even though it currently works in most cases).

[494] avoid calling back to JVM on shared library unload

---

CHANGES.md
src/com/sun/jna/Function.java
src/com/sun/jna/Library.java

Hi, another change for method call performance. Some unnecessary time was spent in Function#invoke(Class returnType, Object[] inArgs, Map options). The method looked up the method object and the parameter types, although this information is already available, when invoking the method from Library$Handler#invoke(Object proxy, Method method, Object[] inArgs). So I refactored both classes a bit so that no unnecessary work is done. In my tests function calls are now measurably faster and produce fewer objects (->less garbage).

Improved function call performance

---

CHANGES.md
src/com/sun/jna/Function.java
src/com/sun/jna/VarArgsChecker.java
test/com/sun/jna/VarArgsCheckerTest.java

I noticed that using reflection for calling the isVarArgs method on java.lang.Method is pretty slow compared to a direct call. So Instead, I implemented a solution based on selection of a concrete subclass, depending whether the method is available or not. In my tests this lead to a 5% increase of method call speed.
This may be a bit controversial, because it needs Java 1.5+ to compile all sources. It does run under Java1.4 though, when compiling with -source and -target set to 1.4 (I checked). So, the maintainers should decide if this is a suitable solution or not.

Changed the way that VarArgs are determined

---

README.md

Changed link to github.io domain.

Fix javadoc link in README.md

---

src/com/sun/jna/Native.java

Is there a reason why these debug flags cannot be changed during runtime?

Make native debug flags toggleable at runtime

---

contrib/platform/test/com/sun/jna/platform/win32/COM/ShellApplicationWindowsTest.java

Per Daniel D's request in [the Google Group thread](https://groups.google.com/forum/#!topic/jna-users/5w8s8T6yFl0), here's a test for issue #520

Test for issue #520

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/LMAccess.java
contrib/platform/src/com/sun/jna/platform/win32/LMShare.java
contrib/platform/src/com/sun/jna/platform/win32/Mpr.java
contrib/platform/src/com/sun/jna/platform/win32/Netapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Winnetwk.java
contrib/platform/test/com/sun/jna/platform/win32/MprTest.java
contrib/platform/test/com/sun/jna/platform/win32/Netapi32Test.java

Added com.sun.jna.platform.win32.Mpr, com.sun.jna.platform.win32.LmShare, and com.sun.jna.platform.win32.Winnetwk
Added ACCESS_* definitions to com.sun.jna.platform.win32.LmAccess
Added NetShareAdd and NetShareDel to com.sun.jna.platform.win32.Netapi32

Added new library Mpr and functions to Netapi32

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Tlhelp32.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java

Kernel32.dll Functions 
---------------------------------
* ProcessIdToSessionId
* LoadLibraryEx
* FindResource
* LoadResource
* LockResource
* SizeofResource
* FreeLibrary
The last 6 are implemented as a single workflow (utility function). It didn't make sense to submit them as individual PRs.
Given a file path, resource type, and resource name, the utility function in Kernel32Util should return a byte array of the resources's content.
ProcessIdToSessionId and LoadLibraryEx have their own tests, and the others are indirectly tested by testing the helper function.

Kernel32.ProcessIdToSessionId and resource extraction functions

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java

This also fixes an embarassing mistake I made in Kernel32Util.getResource().
Like an idiot, I committed it to the branch on my fork, wandered off for a few days, came back, and created the last PR without realizing I'd never run the unit test.

Added EnumResourceTypes and EnumResourceNames to Kernel32

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/WinBaseTest.java

Proposed additions to FILETIME to address #546.
* Rename `toLong()` as `toTime()` and deprecate the former.
* Add a method to return `DWORDLONG` type, from which `longValue()` can be extracted.
If this approach is approved I'll write a test case.

Return 64-bit unsigned integer from FILETIME

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/X11.java
contrib/platform/test/com/sun/jna/platform/unix/X11Test.java

When deriving from a native-mapped struct, need to provide an updated fromNative method

Fix PictFormat assignment error in X11 libraries

---

CHANGES.md
src/com/sun/jna/Native.java
test/com/sun/jna/NativeTest.java

When options get saved, inject the nominal `Library` class (or direct-mapped class) for which the options are in effect.

Ensure enclosing class query shows up properly for cached options

---

CHANGES.md
src/com/sun/jna/CallbackReference.java
test/com/sun/jna/CallbacksTest.java

Ensures that any calling convention set in library options gets propagated to callbacks.
Also includes non-direct callbacks in forced memory reclamation. 
Fixes issue #531

[531] Fix stdcall callback calling convention

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java

Added mapping for Win32 Kernel API GetProcessImageFileName as described in MSDN page: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683217(v=vs.85).aspx.
This method is used to retrieve the full path of an executable of a running process

539: Added Missing Windows kernel32 method: QueryFullProcessImageName

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/IEnumIDList.java
contrib/platform/src/com/sun/jna/platform/win32/COM/IShellFolder.java
contrib/platform/src/com/sun/jna/platform/win32/Guid.java
contrib/platform/src/com/sun/jna/platform/win32/Shell32.java
contrib/platform/src/com/sun/jna/platform/win32/Shlwapi.java
contrib/platform/test/com/sun/jna/platform/win32/COM/IShellFolderTest.java

I needed to wrap IShellFolder so I can enumerate objects in My Computer. Along the way I fixed Guid.REFIID and added a few definitions into other libraries too. The IShellFolder test uses all the added library functions, so they get tested via that.

IShellFolder support

---

contrib/platform/src/com/sun/jna/platform/win32/Shlwapi.java

IShellFolder test was failing because this library didn't inherit from StdCallLibrary.

Make Shlwapi inherit the right class

---

contrib/platform/src/com/sun/jna/platform/win32/COM/COMBindingBaseObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMEarlyBindingObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/Dispatch.java
contrib/platform/src/com/sun/jna/platform/win32/COM/DispatchListener.java
contrib/platform/src/com/sun/jna/platform/win32/COM/DispatchVTable.java
contrib/platform/src/com/sun/jna/platform/win32/COM/IDispatch.java
contrib/platform/src/com/sun/jna/platform/win32/COM/ITypeLib.java
contrib/platform/src/com/sun/jna/platform/win32/COM/IUnknown.java
contrib/platform/src/com/sun/jna/platform/win32/COM/TypeLib.java
contrib/platform/src/com/sun/jna/platform/win32/COM/TypeLibUtil.java
contrib/platform/src/com/sun/jna/platform/win32/COM/Unknown.java
contrib/platform/src/com/sun/jna/platform/win32/COM/UnknownListener.java
contrib/platform/src/com/sun/jna/platform/win32/COM/UnknownVTable.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/CallbackProxy.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/src/com/sun/jna/platform/win32/Shlwapi.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ComEventCallbacks_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ConnectionPointContainer_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/IDispatchTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ITypeLibTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/IUnknownTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/RunningObjectTable_Test.java

Remove a ton of JVM crashes by using REFIID instead of REFIID.ByValue. REFIID is a REference to IID, so most definitely not a ByValue type.
Fixed https://github.com/java-native-access/jna/issues/407 too. Many of the COM tests remain broken, will see if I have time to look at them later. They all need to be ported from MS Word to Shell or something else guaranteed to be installed.

Refiid byvalue

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/LibC.java
contrib/platform/src/com/sun/jna/platform/unix/LibCAPI.java
contrib/platform/src/com/sun/jna/platform/unix/Reboot.java
contrib/platform/src/com/sun/jna/platform/unix/Resource.java
contrib/platform/src/com/sun/jna/platform/unix/X11.java
contrib/platform/test/com/sun/jna/platform/unix/AbstractUnixTestSupport.java
contrib/platform/test/com/sun/jna/platform/unix/LibCTest.java
contrib/platform/test/com/sun/jna/platform/unix/X11Test.java

Added some code for 'libc' API(s) - just to get us started. I only added jUnit tests for _get/setenv_ since I cannot test the others (especially the _reboot_). I can tell you that _reboot_ works since I am using it in another project I wrote and which serves as the trigger for this API.

Initial code for a few Unix 'libc' API(s)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Tlhelp32.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java

* Added Module32First() and Module32Next() mappings to Kernel32
* Added MODULEENTRY32 structure to Tlhelp32
* Added getModules() helper to Kernel32Util

added Module32First and Module32Next to Kernel32

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/VerRsrc.java
contrib/platform/src/com/sun/jna/platform/win32/VersionUtil.java
contrib/platform/test/com/sun/jna/platform/win32/VersionUtilTest.java

It obtains the 'major', 'minor', 'revision', and 'build' version from a given file.
Added unit test for it - it does not require any new Win32 mappings for Version.dll

added VersionUtil class and utility method for obtaining file version information

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Wininet.java
contrib/platform/src/com/sun/jna/platform/win32/WininetUtil.java
contrib/platform/test/com/sun/jna/platform/win32/WininetTest.java
contrib/platform/test/com/sun/jna/platform/win32/WininetUtilTest.java

Adds Wininet interface with the following functions in Wininet.dll:
* `FindFirstUrlCacheEntry`
* `DeleteUrlCacheEntry` 
* `FindCloseUrlCache`
* `FindNextUrlCacheEntry`
Also includes the `INTERNET_CACHE_ENTRY_INFO` structure in Wininet.h
Also includes a helper function for parsing WinInet's / IE's cache.
And last but not least, also includes tests for helper util method and all individual functions in Wininet.

Initial support for Wininet.dll and enumeration of its' / IE's cache

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Psapi.java
contrib/platform/src/com/sun/jna/platform/win32/Shell32.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/PsapiTest.java
contrib/platform/test/com/sun/jna/platform/win32/Shell32Test.java

Added `EnumProcessModules`, `GetModuleInformation`, `GetProcessImageFileName` to `com.sun.jna.platform.win32.Psapi` and `ExtractIconEx` to `com.sun.jna.platform.win32.Shell32`
Added constants to `com.sun.jna.platform.win32.WinNT`

Additional Win32 Mappings: Added 3 functions to Psapi and 1 function to Shell32

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Winspool.java

Values for `Attributes` and `Status` from PRINTER_INFO_2 structure, among others.
Reference links:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd162845%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/aa394363%28v=vs.85%29.aspx
http://sourceforge.net/p/mingw-w64/mingw-w64/ci/91eefe184bed498e732e274ccefa56fcd95e4473/tree/mingw-w64-headers/include/winspool.h
https://www.rpi.edu/dept/cis/software/g77-mingw32/include/winspool.h
http://www.rdos.net/svn/tags/V9.2.5/watcom/bld/w32api/include/winspool.mh

Added printer attributes and status

---

CHANGES.md
native/testlib.c
src/com/sun/jna/Function.java
test/com/sun/jna/VarArgsTest.java

As discussed on https://github.com/java-native-access/jna/issues/463

Promote float varargs to double

---

contrib/platform/src/com/sun/jna/platform/win32/OaIdl.java

The initialization order of the static fields in OaIdl.INVOKEKIND is broken. When INVOKEKIND is initialized the static fields also hold instances of INVOKEKIND. The constructors are called before the necessary definition of FIELDS is available. This results in the stacktrace:
**java.lang.ExceptionInInitializerError
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at java.lang.Class.newInstance(Class.java:442)
at com.sun.jna.Structure.newInstance(Structure.java:1807)**
at com.sun.jna.Structure.newInstance(Structure.java:1793)
at com.sun.jna.Structure.size(Structure.java:1062)
at com.sun.jna.Native.getNativeSize(Native.java:1208)
at com.sun.jna.Structure.getNativeSize(Structure.java:2114)
at com.sun.jna.Structure.getNativeSize(Structure.java:2104)
at …

OaIdl.INVOKEKIND can't be instantiated (fixes failing TypeLibUtilTest)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/ITypeLib.java
contrib/platform/src/com/sun/jna/platform/win32/COM/TypeLib.java
contrib/platform/src/com/sun/jna/platform/win32/COM/TypeLibUtil.java
contrib/platform/src/com/sun/jna/platform/win32/WTypes.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ITypeLibTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/TypeLibUtilTest.java

- fix wrong function signature in ITypeLib/TypeLib for FindName/IsName
and adjust callers
- TypeLib#ReleaseLibAttr did not pass parameter to native method
- LPOLESTR.ByReference is derived from wrong type (BSTR instead of LPOLESTR)
- Fix/Add unittests

Improve binding of TypeLib bindings

---

src/com/sun/jna/CallbackReference.java

CallbackReference has some useful methods:
- public static Callback getCallback(Class<?> type, Pointer p) { ... }
- public static Pointer getFunctionPointer(Callback cb) { ... }
But they can't be used because the class is not public. This little patch makes the class public.

making CallbackReference accessible (public)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/COMBindingBaseObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/test/com/sun/jna/platform/win32/COM/IDispatchTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/HybdridCOMInvocationTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/RunningObjectTable_Test.java

It was found, that calling InchesToPoints method from word type library
failed. Research lead to 
https://www.delphitools.info/2013/04/30/gaining-visual-basic-ole-super-powers/
https://msdn.microsoft.com/en-us/library/windows/desktop/ms221486(v=vs.85).aspx
Summary: there are methods in the word typelibrary that require both
PROPERTYGET _and_ METHOD to be set. With only one of these set the call
fails.
The article from delphitools argues, that automation compatible libraries
need to be compatible with VisualBasic which does not distingish methods
and property getters and will set both flags always.
The MSDN article advises this behaviour: "[...] Some languages cannot 
distinguish between retrieving a property and calling a method. In this 
case, you should set the flags …

Allow calling COM methods/getters requirering hybrid calling (METHOD+PROPERTYGET convention)

---

CHANGES.md
native/dispatch.c
src/com/sun/jna/Native.java
test/com/sun/jna/NativeTest.java

Add support for determining 'bool' size

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java

The code was not releasing properly SID memory allocated by the _ConvertSidXXX_ methods.

Make sure SID related memory is properly released once no longer required

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Crypt32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32Test.java
contrib/platform/test/com/sun/jna/platform/win32/VersionTest.java

The current code calls _Local/GlobalFree_ without checking that they succeeded.

Added Kerne32Util method to facilitate checking that calls to LocalFree/GlobalFree are successful

---

CHANGES.md
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
src/com/sun/jna/NativeLibrary.java

Corrected required overrides in the "short-circuit" code

Fixed issue #604: Kernel32#GetLastError() always returns ERROR_SUCCESS

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Crypt32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/VersionTest.java

Adhere to the standard that _Util_ classes throw exceptions if execution failure

Kernel32Util#freeLocal/GlobalMemory always throws Win32Exception if failed

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Win32Exception.java
contrib/platform/test/com/sun/jna/platform/win32/Win32ExceptionTest.java
src/com/sun/jna/LastErrorException.java

It is only logical since this is what _Win32Exception_ is actually used for

Make Win32Exception extend LastErrorException

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/W32FileMonitor.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/PsapiTest.java
contrib/platform/test/com/sun/jna/platform/win32/Secur32Test.java

Provide bolierplate template for code that is supposed to close a handle and check the returned error code if failed to do so

Added standard Kernel32Util#closeHandle method that throws an exception if failed to close the handle

---

contrib/platform/src/com/sun/jna/platform/win32/COM/tlb/imp/TlbCoClass.java
contrib/platform/src/com/sun/jna/platform/win32/COM/tlb/imp/TlbDispInterface.java

This is only manually tested and the resulting code was only superficially checked. I noticed the problem in the past when I first looked at JNA as a potential way to call COM code.
The commit changes the TlbImp to change from failing with a NullPointerException to producing code.
Checked with the OLE 2.0 and Word 15 typelib.
I don't consider this important enough for a CHANGES.md entry.

Fix NullPointer Exception in TlbCodegenerator

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/util/CallbackProxy.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Factory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/IDispatch.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/annotation/ComProperty.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/IDispatchTest.java

The ProxyObject implements several base interfaces directly, but the methods were not correctly handled. This pull modifies the InvocationHandler part to select methods based on declaration interface with direct method invocation, instead of manually redirecting each method.
The second part adds more robustness (and speed as sideeffect) to ProxyObject by using dispIDs if they are available, making reflection via GetIDsByName unnessary.

Allow access to base interfaces via ProxyObject and improve binding

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/util/CallbackProxy.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/src/com/sun/jna/platform/win32/Variant.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/IDispatchTest.java

ProxyObject and Callback both use the Convert class as helper to convert
java object to/from VARIANT. This change adds more flexibility and adds
tests to fixate and check conversion.

Make conversion to/from java in c.s.j.p.win32.COM.util more flexible

---

contrib/platform/src/com/sun/jna/platform/win32/COM/COMUtils.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/CallbackProxy.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/src/com/sun/jna/platform/win32/Guid.java
contrib/platform/test/com/sun/jna/platform/win32/COM/COMUtilsTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacks_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java

- FormatMessage throws a LastErrorException when HRESULT can't be resolved
- Primitives + void can't be returned from COM calls (failing the final cast)
- REFIID#equals was in past based on content, this is now the case again
Please see the individual commits for details, the commits again form seperate units for each part.

Followup fixes for some regressions

---

www/Contributing.md

There is a minor formatting error that breaks the link to the Android docs.

Fix link to Android doc

---

CHANGES.md
src/com/sun/jna/Native.java
test/com/sun/jna/CallbacksTest.java
test/com/sun/jna/NativeTest.java
test/com/sun/jna/ReturnTypesTest.java
test/com/sun/jna/StructureTest.java

Per the discussion [here](https://groups.google.com/d/msg/jna-users/FdcRn_F6Qts/aG-o8AZkBgAJ), the default encoding used for Java strings being passed to native interfaces should not be hard-coded as UTF-8, but instead should be the platform's native encoding.
This patch takes the native encoding from `Charset.defaultCharset()` and updates the relevant tests. In addition, I have ensured that the tests pass even when the default charset is Cp1252 (the default on English Windows); special care was required in this case because the tests uses characters that cannot round-trip between Unicode and Cp1252, and it is not clear that choosing round-trippable characters would still result in a meaningful test when Unicode is supported.
Note that I was not able to actually run the tests on Windows …

Use platform native encoding by default, not UTF-8

---

CHANGES.md
build.xml

I have missed a simple way to activate my recently built jna artifacts so I can use them in other maven projects. So I would appreciate it to add an ant target for doing so after the "dist" build

New ant target for installing JNA artifacts in local m2-repository

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/COMBindingBaseObject.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ComExceptionWithoutInitializationTest.java

The exception thrown from COMBindingBaseObject when instatiation fails
is misleading:
COM object with CLSID {0002DF01-0000-0000-C000-000000000046} not registered properly!
In the concrete case COM was not properly initialized, the same error now
reports (in german locale):
CoInitialize wurde nicht aufgerufen.(HRESULT: 800401f0) (puArgErr=)
For english locale this should be along the lines of:
CoInitialize was not called.(HRESULT: 800401f0) (puArgErr=)
The message now points out the correct problem (as far as the windows
error code translation works) and the HRESULT can be used for a locale
independend report + search.
Closes #646
Please note: The change in COMBindingBaseObject looks worse in the diff, than it is. The two constructors (the clsid and the progid ones) were mostly duplicated …

Exception from COMBindingBaseObject swallows real reason + HRESULT

---

CHANGES.md
contrib/msoffice/src/com/sun/jna/platform/win32/COM/util/office/Excelautomation_KB_219151_Mod.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Factory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConfigurateLCID_Test.java

The system/user default LCID is not always the best/correct value to
use for COM invocations. One example is excel, if the default user
LCID is used, formulas need to be coded in the language of the user.
This commit moves the LCID handling into the factory, so LCID can be
overridden per instantiated factory.
A unittest was added, but marked as ignored, as the test is depending
on the installed excel locale and only usable on non-english locales.
(test was run on a german excel version)
In addition to the unittest the msoffice sample was adjusted to be
usable on non-english locales (manually tested on same german excel
version specified above).
Closes: #659

Consolidate LCID handling for COM calls invoked via ProxyObject

---

build.xml
pom-jna-platform.xml
pom-jna.xml
www/PublishingToMavenCentral.md

After the announced shutdown of the java.net/kenai hosting by oracle, JNA needed a new home for pushing binaries to maven central. The  OSSRH (OSS Repository Hosting) service offered by sonatype was asked to provide the new home, and that request was granted.
The release process is very similar to the deployment on the java.net infrastructure and the necessary changes can be found below.
The first snapshots were pushed to the OSSRH to test deployment, the POMs were modified to contain my data to allow uploading, as sonatype requires the developer information to be present (I asume it is verified then).
Further uploaders are possible, but the old java.net accounts can't be used for that. Sonatype requires uploaders to have an account in their jira (this is synchronized to their nexus …

Prepare publishing binaries to maven central via sonatype OSS repository hosting

---

contrib/platform/src/com/sun/jna/platform/win32/COM/util/CallbackProxy.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ComThread.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/EnumMoniker.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Factory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ObjectFactory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/RunningObjectTable.java
contrib/platform/test/com/sun/jna/platform/win32/COM/EnumMoniker_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/HybdridCOMInvocationTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/IDispatchTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/RunningObjectTable_Test.java
contrib/platform/test/com/sun/jna/platform/win32/SAFEARRAYTest.java

The removal of the ComThread broke one use case of the win32.com.util 
packages. It was now necessary to explicitly handle threading and COM
initialization.
The intention was to broaden the possible use cases of the win32.com.util
package.
This changeset tries to reinstantiate the old functionality while keeping
the benefits of the intended change by introducing a new baseclass.
Closes #651

Reintroduce ComThread and move base functions into ObjectFactory

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Shell32.java
contrib/platform/test/com/sun/jna/platform/win32/Shell32Test.java

Added functions to Shell32 wrapper which are useful Desktop integration for Java GUI applications (on Windows 7 and higher).
- `SetCurrentProcessExplicitAppUserModelID`
- `GetCurrentProcessExplicitAppUserModelID`

Shell32.SetCurrentProcessExplicitAppUserModelID

---

.travis.yml

Work around homebrew/glibtoolize interaaction bug on OSX El Capitain.
See if [this](https://github.com/libgd/libgd/issues/266) works, at least until the Travis folks get their OSX environment fixed up.

[Travis CI] OSX build error workaround

---

.gitignore
CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Ddeml.java
contrib/platform/src/com/sun/jna/platform/win32/DdemlUtil.java
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/User32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/src/com/sun/jna/platform/win32/WinUser.java
contrib/platform/test/com/sun/jna/platform/win32/DdemlTest.java
contrib/platform/test/com/sun/jna/platform/win32/DdemlUtilTest.java

Primary intention of this PR is binding the DDEML and adding a convenience wrapper
for that. The two other commits support this effort:
- The clipboard formats are used in the DDEML bindings as format specifier
- The MessageLoopThread implementation is the basis for the StandaloneDdeClient, that takes care of running a message loop by itself.

Bind DDEML (Dynamic Data Exchange Management Library)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/User32.java

Added GetClientRect function to get the size of the Window excluding the borders.

Added GetClientRect

---

native/libffi/msvcc.sh

Prevents wrong quote surrounding that leads to 
> fatal error C1083: Cannot open include file: 'fficonfig.h': No such file or directory

Correct Windows/Cygwin build error as reported in issue #603

---

native/dispatch.c
native/dispatch.h
native/protect.h
native/snprintf.h

This `_XOPEN_SOURCE` macro was used after some standard header includes. [Which is not POSIX compliant](http://pubs.opengroup.org/onlinepubs/007904975/functions/xsh_chap02_02.html).
Depending on libc implementation, if one of theses headers were using `<string.h>`, the later presence of `_XOPEN_SOURCE` macro would't matter as the `<string.h>` would't be included again.
This prevents uninitialized buffer from being passed to `printf` (search for `STR_ERROR` in dispatch.c). 
Signed-off-by: David Keller <david.keller@enyx.fr>

Fix #392 - Ensure XSI-compliant strerror_r is used.

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
src/com/sun/jna/Function.java

... and not by name (available on win32)

Add GetProcAddress to allow accessing functions exported by ordinal

---

contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/User32Util.java

The MSDN advises to check the return value of GetMessage, instead of
blindingly spinning the main loop:
https://msdn.microsoft.com/de-de/library/windows/desktop/ms644936(v=vs.85).aspx
If GetMessage returns -1 this indicates an error and needs to be handled.
By default the MainLoop will exit on an error and log this condition via
java.util.logging. Users can choose to subclass MessageLoopThread to
customize the behavior.

Update User32Util#MessageLoopThread to handle error condition of GetMessage

---

CHANGES.md
src/com/sun/jna/Memory.java
test/com/sun/jna/MemoryTest.java

Ensure disposed memory is removed from Memory#allocatedMemory map

---

contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/OaIdl.java
contrib/platform/src/com/sun/jna/platform/win32/Variant.java
contrib/platform/test/com/sun/jna/platform/win32/VariantTest.java

- SAFEARRAY now implements Closeable - on recent java versions this
allows handling SAFEARRAY using try-with-resource
- When wrapped in a VARIANT the correct type is not VT_SAFEARRAY, but
VT_ARRAY or'd with the type of the SAFEARRAY elements
- VT_SAFEARRAY is not a valid value for VARIANT:
https://msdn.microsoft.com/de-de/library/windows/desktop/ms221170(v=vs.85).aspx
- When used with com.sun.jna.platform.win32.com.util.ProxyObject
SAFEARRAY is correctly wrapped into a VARIANT

Improve SAFEARRAY (Closeable, Autoconversion, VARIANT wrapping)

---

contrib/platform/src/com/sun/jna/platform/win32/OaIdl.java
contrib/platform/test/com/sun/jna/platform/win32/VariantTest.java

It was interpreted, that the VT_DATA resolution was limited to hour
increments. At the time of this patch the whole way can't be reconstructed,
but tests in a production environment, comparing different COM
implementations (JIntegra and JNA) exposed the different interpreations.
The current implementation follows the advise from:
https://blogs.msdn.microsoft.com/joshpoley/2007/12/19/datetime-formats-and-conversions/
and the definition from (though this description does not show an example handling minutes):
https://msdn.microsoft.com/de-de/library/cc237601.aspx

Correct assumption about resolution of VT_DATE

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Implement SetThreadExecutionState

---

CHANGES.md
native/dispatch.c

mingw used to directly use the msvcrt implementation of swprintf which
does does not match the ANSI version. This was fixed in mingw-64 and
so this special case has to be removed.

Fix build with mingw-64 on windows

---

src/com/sun/jna/Structure.java

The javadoc of `Structure` mentions that autoRead is applied before a native function call, and autoWrite after; it is exactly the opposite.

Fix mix-up of when autoRead and autoWrite is applied

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinioctlUtil.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Removed unneeded interface and converted defintions into regular integers.

Modified WinioctlUtil for simplicity

---

contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

The test was based on the wrong assumption, that the ordinal values of
functions in kernel32.dll are stable.

Disable testGetProcAddress test

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/NTStatus.java
contrib/platform/src/com/sun/jna/platform/win32/NtDll.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/NtDllTest.java

**Advapi32**
* GetSecurityDescriptorOwner
* SetSecurityDescriptorOwner
* GetSecurityDescriptorGroup
* SetSecurityDescriptorGroup
* GetSecurityDescriptorControl
* SetSecurityDescriptorControl
* GetSecurityDescriptorDacl
* SetSecurityDescriptorDacl
* MakeSelfRelativeSD
* MakeAbsoluteSD
* EqualSid
* InitializeSecurityDescriptor
* InitializeAcl
* AddAce
* AddAccessAllowedAce
* AddAccessAllowedAceEx
* GetAce
**NtDll**
* RtlNtStatusToDosError

Adding security functions and RtlNtStatusToDosError to NtDll

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Secur32.java
contrib/platform/src/com/sun/jna/platform/win32/Sspi.java
contrib/platform/test/com/sun/jna/platform/win32/Secur32Test.java

Added Secur32#QueryContextAttributes

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java

The custom logic which I removed, did not account for a missing NUL terminator. Plus, it is better to use logic already in the code base (e.g. `Native.toString()`).

Call `Native.toString()` in `#getFileName()` & `#getAlternateFileName()`

---

CHANGES.md
src/com/sun/jna/Function.java
test/com/sun/jna/VarArgsTest.java

The change in 50eb820c129d298c26035f98e6a93aed9fc52257 introduces
the detection of the count of the fixed parameters of a VarArgs call.
The logic detecting whether this call was even a VarArgs call was
changed to be true if fixed parameter count is not null. This is
not correct, as the method call could contain only fixed parameters
or a VarArgs call could be done without fixed parameters.
Closes: #763

Fix calling functions with only VarArgs (without fixed parameters)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/GDI32Util.java

Instead of using setRGB on a newly created BufferedImage, create a from the pixel buffer and create the BufferedImage from that.
This is the same way that java.awt.Robot does it.

Improve speed of GDIUtils.getScreenshot by ~30%

---

CHANGES.md
contrib/platform/build.xml

The netbeans copylibs task copies the dependend libraries and modifies
the jar MANIFEST.MF to reference the copied libs.
The task is reimplemented in the build.xml to override the base definition
in build-impl.xml, as build-impl.xml comes from the netbeans project template,
future updates could destroy the change if it is not done in build.xml, which
is considered project depended.
Closes: #776

Do not include ClassPath attribute in jna-platform.jar

---

test/com/sun/jna/win32/W32APIMapperTest.java

The choosen character \u0444 (CYRILLIC SMALL LETTER EF) is not present
in all CP* charsets. This change switches to \u203a 
'SINGLE RIGHT-POINTING ANGLE QUOTATION MARK': ›, which was found to
be present in CP1250-CP1258.
Closes: #779

Fix W32APIMapperTest failing on non-CP1252 encodings

---

contrib/platform/src/com/sun/jna/platform/win32/DdemlUtil.java

Hi,
Several DDE methods have two flavors, one with Ddeml.HSZ parameters and the other with Strings which are more convenient to use. The javadoc for the methods using a String is sometimes incorrect and states that a `0L` value can be used (instead of null).

Javadoc fix for the DDE methods using a String instead of Ddeml.HSZ

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/OaIdlUtil.java
contrib/platform/test/com/sun/jna/platform/win32/SAFEARRAYTest.java

The declared bounds of the SAFEARRAY can be ignored, as the SAFEARRAY
is continuous and the toPrimitiveArray maps it to a plain "zero" based
java array. The access to the SAFEARRAY does not happen through the 
accessor methods, but via direct access to the underlying memory.
Closes: #785

OaIdlUtil#toPrimitiveArray fails if dimension bounds are not 0-based

---

contrib/platform/src/com/sun/jna/platform/win32/User32Util.java

Hi,
I'd like to suggest the addition of an explicit thread name to the message loop in User32Util. This makes the thread clearly identifiable in debugging tools such as VisualVM or JProfiler.
Thank you

Descriptive thread name for the User32Util message loop

---

build.xml

Not having a targetSdkVersion in the AndroidManifest means that the manifest merge tool will add some implicit permissions to Android apps. See [here](https://developer.android.com/studio/build/manifest-merge.html).
This is possible to override in the app, but is annoying to track down.
Also I'm pretty sure JNA by itself doesn't need these permissions, and that adding a targetSdkVersion shouldn't hurt anyone.

Add targetSdkVersion to AndroidManifest.

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java

WORD is defined to hold 16 bit on windows, so it needs to be accessed 
as short (getShort()).
Closes: #795

com.sun.jna.platform.win32.WinDef.WORDByReference holds a WORD (16bit)

---

www/PointersAndArrays.md

Am I wrong in adding this clarification? Looking at [`dispatch.c`](https://github.com/java-native-access/jna/blob/master/native/dispatch.c#L1305) it seems to me that only direct buffers can provide this guarantee. `Get##TYPE##ArrayElements` don't offer this guarantee once you do the `Release##TYPE##ArrayElements` right?

Pointer documentation clarified

---

CHANGES.md
contrib/platform/build.xml

The java 9 module system expects the main class to reside in the same
jar, as the MANIFEST.MF. For the jna.jar the use case is valid to 
retrieve the current version of JNA, as jna.jar must be available
to run jna-platform.jar, there is no use-case to have the Main-Class
defined.
As reference the explanation from the jigsaw-dev mailing list:
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-April/012151.html

Main-Class in jna-platform.jar collides with java 9 module system

---

CHANGES.md
build.xml
contrib/platform/src/com/sun/jna/platform/win32/BaseTSD.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMInvoker.java
contrib/platform/src/com/sun/jna/platform/win32/WTypes.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/src/com/sun/jna/platform/win32/WinReg.java
contrib/platform/src/com/sun/jna/platform/win32/WinUser.java
src/com/sun/jna/CallbackReference.java
src/com/sun/jna/Function.java
src/com/sun/jna/Memory.java
src/com/sun/jna/Native.java
src/com/sun/jna/NativeLibrary.java
src/com/sun/jna/Pointer.java
src/com/sun/jna/StringArray.java
src/com/sun/jna/Structure.java
src/com/sun/jna/ptr/PointerByReference.java
src/com/sun/jna/win32/StdCallFunctionMapper.java
test/com/sun/jna/HeadlessLoadLibraryTest.java
test/com/sun/jna/LibraryLoadTest.java
test/com/sun/jna/PointerTest.java
test/com/sun/jna/StructureBufferFieldTest.java
test/com/sun/jna/StructureTest.java
test/com/sun/jna/UnionTest.java
test/com/sun/jna/VMCrashProtectionTest.java
test/com/sun/jna/win32/W32APIMapperTest.java

There are two vectors addressed:
- Pointer and Native classes are prone to deadlocks when loaded from different Threads. The cycle can be broken by removing the Pointer#SIZE attribute and instead using the Native#POINTER_SIZE value. From the commit message:
> Remove Pointer#SIZE replaced by Native#POINTER_SIZE to prevent classloading deadlock
> 
> If Pointer and Native class are concurrently initialized, a deadlock
> results:
> 
> - The static initializer block of Pointer uses Native#POINTER_SIZE
>   to initialize its SIZE value
> - The Native#initIDs method loads the Pointer class via JNI to find
>   its ClassID and MethodIDs
> 
> Both threads enter the initialization lock for their corresponding class
> for initialization to succeed both classes also need an initialized
> version of the …

Bugfix deadlock when Pointer and Native classes are loaded from different threads in parallel

---

CHANGES.md
native/dispatch.c
test/com/sun/jna/ArgumentsMarshalTest.java
test/com/sun/jna/DirectArgumentsMarshalTest.java

This is consistent with how these are handled in [interface mapping](https://github.com/java-native-access/jna/blob/b37a652c/native/dispatch.c#L581).
Also boolean is `ffi_type_uint32` everywhere in the source code, except [here](https://github.com/java-native-access/jna/commit/8f2e773a).

Direct Mapping for boolean arrays

---

src/com/sun/jna/Platform.java
test/com/sun/jna/PlatformTest.java

The ELFAnalyser analyses the java binary to determine, whether the
hardfloat/softfloat flags are set. This causes issues if a security
manager is in place and limits file accessibility.
The JNA code base needs read access on the /proc/self/exe symlink and
the referenced binary.
This change reduces the cases where the executing binary is read. On
platforms, that don't need it, the detection step is skipped.
Close: #825

Only analyse binary to determine hardfloat vs. softfloat on arm

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/IUnknown.java
contrib/platform/src/com/sun/jna/platform/win32/Ole32.java
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32ConsoleTest.java
contrib/platform/test/com/sun/jna/platform/win32/Shell32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java

- MonitorFromPoint takes a structure, not a reference to a structure,
so function definition was wrong
- The last to "KnownFolters" don't resolve on Win10
- cleanup javadoc warnings

 Fix unittests (IShellFolderTest#testEnumObjects) still fails on amd64) 

---

build.xml

(unmappable character for encoding ascii)

Compilation of unittests fails in debian squeeze chroot

---

README.md

I want to add own [bolt-jna](https://github.com/protonail/bolt-jna) project to 'Projects Using JNA' section and update information about [leveldb-jna](https://github.com/protonail/leveldb-jna) project.

Add bolt-jna project to 'Projects Using JNA' section

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/TypeLibUtil.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/OleAuto.java
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/src/com/sun/jna/platform/win32/Variant.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
src/com/sun/jna/Native.java
src/com/sun/jna/Pointer.java
src/com/sun/jna/Structure.java
src/com/sun/jna/overview.html
test/com/sun/jna/NativeTest.java

With JNA entering a new major version API breaches are possible. In the discussion around PR #839 it was made clear, that clearing up the code should be a priority. In consequence that attached changes remove all deprecated elements.
All elements have better replacements, which are document in the changelog.
There is one method, that is deprecated, but not removed:
`Native#getDirectByteBuffer`
This method was removed from the public interface (visibility changed from public to private) to retain the compatibility at the Java<->C interface. Removing the above declaration completely would require a full rebuild of all native binaries without any benefits.

Cleanup deprecated elements

---

src/com/sun/jna/Native.java
test/com/sun/jna/NativeTest.java

It was possible to pass a non-library class into this method and get a runtime exception, when the same check can be done at compile-time, so this fix changes it to be done at compile-time.
After erasure, with this change the return type changes from `Object` to `Library`. So as far as backwards compatibility:
1. If you were assigning the result to `Object`, that will still work
2. If you were passing something that wasn't a `Class<? extends Library>`, your code will now not compile, instead of failing at runtime.
3. I can't remember the rules for binary compatibility.
Fixes #822.

Changing Class<T> to Class<T extends Library> for Native.loadLibrary

---

CHANGES.md
src/com/sun/jna/ELFAnalyser.java
test/com/sun/jna/ELFAnalyserTest.java

Hi, i will send PR related ELFAnalyser. Please refer to the followings. 
[ELF for the ARM Architecture](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0044f/IHI0044F_aaelf.pdf) says 
```
If both
EF_ARM_ABI_FLOAT_XXXX bits are clear, conformance to the base
procedure-call standard is implied.
```
The base standard is software-floating. But now, the condition of armSoftFloat is whether EF_ARM_ABI_FLOAT_SOFT is exists or not. So, if jna is called from a program based on JDK without both EF_ARM_ABI_FLOAT_XXXX bits (e.g Oracle Java Embedded, a homemade JDK), jna select lib for hardware-floating and do not work correctly. 
So, I changed the condition of armSoftFloat.

change armSoftFloat condition in ELFAnalyser

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/COMLateBindingObject.java

Variants that hold strings utilize a BSTR. BSTRs are special in the sense, that
they are allocated by SysAllocString and freed by SysFreeString and the memory
needs to be explicitly cleared.
For Variants this is handled by VariantClear. VariantClear clears the data
contained in the Variant and frees that data (not the Variant itself!). The
Variant structure is caller allocated and in JNA located in auto-allocated
memory and does not need to be explicitly freed.
This closes #867

Fix memory leak in COMLateBindingObject#getStringProperty

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/LibCAPI.java
contrib/platform/src/com/sun/jna/platform/win32/Winsock2.java
contrib/platform/test/com/sun/jna/platform/unix/LibCTest.java
contrib/platform/test/com/sun/jna/platform/win32/Winsock2Test.java

Fix wrong mapping of libc function gethostname, sethostname, 
getdomainname  and setdomainname. The functions are defined as:
int getdomainname(char *name, size_t len);
int setdomainname(const char *name, size_t len);
int gethostname(char *name, size_t len);
int sethostname(const char *name, size_t len);
and a C char[] maps by default to a byte[] in java.
In addition bind the winsock gethostname function:
com.sun.jna.platform.win32.Winsock2.gethostname(byte[], int)
This closes #871

Improve hostname functions

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Crypt32Util.java
contrib/platform/src/com/sun/jna/platform/win32/GDI32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Win32Exception.java
contrib/platform/src/com/sun/jna/platform/win32/WininetUtil.java
contrib/platform/src/com/sun/jna/platform/win32/WinspoolUtil.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/PsapiTest.java
contrib/platform/test/com/sun/jna/platform/win32/Win32ExceptionTest.java
test/com/sun/jna/ELFAnalyserTest.java

This is a partial fix to restore Java 6 compatibility:
- unittests for jna can be compiled with a Java 6 JDK
- the jna-platform can be compiled with a Java 6 JDK
- the unittests for the jna-plaform still require a Java 7 JDK

Java 6 compatibility

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Winevt.java
src/com/sun/jna/CallbackReference.java
src/com/sun/jna/Function.java
src/com/sun/jna/Native.java
src/com/sun/jna/Pointer.java
src/com/sun/jna/Structure.java
test/com/sun/jna/StructureTest.java

The signature was: `Structure newInstance(Class<?> type)` requiring
an explicit cast after the call. The the new signature introduces a 
type parameter `T` with an upper bound of `com.sun.jna.Structure`: 
```java
<T extends Structure> T newInstance(Class<T> type)
```
The companion, that takes an init pointer was also updated:
```java
<T extends Structure> T newInstance(Class<T> type, Pointer init)
```
Closes: #889

Tighten the generic bounds for Structure#newInstance

---

CHANGES.md
contrib/msoffice/src/com/sun/jna/platform/win32/COM/office/MSOfficeDemo.java
contrib/platform/nbproject/project.properties
contrib/platform/src/com/sun/jna/platform/win32/COM/COMBindingBaseObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMException.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMInvokeException.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMUtils.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Factory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/IConnectionPoint.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ObjectFactory.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectObjectFactory_Test.java

Please see the details of the commits.

Update COMException to contain HRESULT and introduce COMInvokeException

---

src/com/sun/jna/NativeLibrary.java

Due to https://github.com/java-native-access/jna/issues/914 I fixed 'Improper Resource Shutdown or Release' flaw from the report.
@matthiasblaesing FYI.

Fix for resource leak on exception

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/util/IConnectionPoint.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksObjectFactory_Test.java

With the added @ComInterface annotation the IConnectionPoint interface
can be retrieved via the IUnknown#queryInterface method.

Add @ComInterface anntation to IConnectionPoint

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java

Adds the [`RegConnectRegistry`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724840.aspx) function mapping to Advapi32. This function is used to connect to remote machines' registries.
I added a test case for the function, but to be completely fair, I'm not 100% sure if the `\\localhost` UNC path works. The test case could be edited to pass in `null` for the name, but then the test doesn't guarantee that the first parameter is a string.

Add RegConnectRegistry to Advapi32 mappings

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java

As discussed in #947 this is the agreed upon successor.

Enable retrieval of ACL containing unspported ACEs

---

CHANGES.md
ant-tools-src/com/sun/jna/BuildArmSoftFloatDetector.java
src/com/sun/jna/ELFAnalyser.java
src/com/sun/jna/Platform.java
test/com/sun/jna/ELFAnalyserTest.java

This is an update to PR 863: Old toolchains produce binaries without
hard-/softfloat markers. Rasbian is missinng the markers and the oracle 
JDK is also affected.
For hardfloat detection now also the Arm EABI section is also considered.
If either the elf hardfloat flag is set or the Arm EABI section indicates
hardfloat the binary is reported as hardfloat.

Use Arm EABI section to detect hard-/softfloat usage

---

contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/OaIdl.java
contrib/platform/src/com/sun/jna/platform/win32/Variant.java
contrib/platform/src/com/sun/jna/platform/win32/WTypes.java

A SAFEARRAY byref that is wrapped in a VARIANT is a **SAFEARRAY. To
model this in JNA a pseudo structure SAFEARRAYByReference is introduced.
This approach is used, so that the referenced SAFEARRAY is read after
a native call.
To make it possible to pass a SAFEARRAYByReference and an IntByReference
through the ProxyObject helper, c.s.j.platform.win32.COM.util.Convert
is modified to reflectivly invoke a matching VARIANT constructor.
This change was manually tested with the GdPicture.NET library using
ProxyObject and COMLateBindingObject based binding.

Fix SAFEARRAY ByReference in VARIANT

---

contrib/platform/src/com/sun/jna/platform/unix/solaris/LibKstat.java

Adding a javadoc to note the mapping to `kstat_ctl_t` is not thread safe.  See https://github.com/oshi/oshi/issues/493 for background.

Document synchronization requirement for KstatCtl

---

contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Implement Windows Mutex functions (CreateMutex, OpenMutex, ReleaseMutex)

---

CHANGES.md
build.xml
contrib/platform/build.xml

This adds version declarations to each exported package in the
OSGi metadata. This allows users to specify that they want a
specific version (or range of versions) of JNA in their OSGi
applications/libraries.
Fix #975

Add package versions to OSGi metadata

---

contrib/platform/src/com/sun/jna/platform/win32/IPHlpAPI.java
contrib/platform/test/com/sun/jna/platform/win32/IPHlpAPITest.java

While the `GetNetworkParams` testcase in #983 worked fine on my Windows7 machine, it created Invalid Access Errors on Win 10, probably related to a combination recursive pre-reading of ByReference structures in the constructor, and local thread caching.  See JNA mailing list thread for details.  Bottom line: the `IP_ADDR_STRING` linked list needs to be mapped as a `Pointer` and the linked list traversed manually.

Fix bug with recursive IP_ADDR_STRING ByReference

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/PdhUtil.java
contrib/platform/test/com/sun/jna/platform/win32/PdhTest.java

The util methods I submitted in #973 do not handle zero-length results (e.g., no counters or instances) well, throwing an `IllegalArgumentException` when attempting to instantiate `Memory`.  I've added checks to return sane values.
Also I've added a Util method that looks up the counter index from the English name using the registry, to permit easier localization of counter strings.

Zero-check PDH counter and instance lists, add English index lookup

---

.travis.yml
appveyor.yml
contrib/platform/src/com/sun/jna/platform/win32/Pdh.java
contrib/platform/src/com/sun/jna/platform/win32/PdhUtil.java
contrib/platform/test/com/sun/jna/platform/win32/AbstractWin32TestSupport.java
contrib/platform/test/com/sun/jna/platform/win32/COM/EnumMoniker_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ITypeLibTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacks2_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ComEventCallbacksObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConfigurateLCID_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/HybdridCOMInvocationTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/IDispatchTest.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectObjectFactory_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/RunningObjectTable_Test.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/PdhTest.java
contrib/platform/test/com/sun/jna/platform/win32/SAFEARRAYTest.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Win32ServiceDemo.java
contrib/platform/test/com/sun/jna/platform/win32/WinspoolTest.java
contrib/platform/test/com/sun/jna/platform/win32/WinspoolUtilTest.java

Running the JNA unittests on the appveyor CI system shows, that implicit assumptions
in the unittests don't hold everywhere. There are:
- corner cases in the behavior of Win32 functions
- missing dependencies (several of the COM tests depend on one of the office products)
- wrong invocations (the Win32DemoService picks up a system wide installed old JNA dll)
- disabled service 
and so on.
The referenced commits either express the assumptions as junit assumption (causing the
affected tests to be skipped) or fix/improve the behavior.
Closes: #685

Enhance stability of tests and prepare for inclusion of appveyor

---

contrib/platform/src/com/sun/jna/platform/win32/WTypes.java

LPWSTR.ByReference currently extends BSTR, which seems to be a typo (copy-pasted BSTR.ByReference?). Instead, LPWSTR.ByReference should extend LPWSTR to follow the typical ByReference subclass paradigm.

Change LPWSTR.ByReference to extend LPWSTR instead of BSTR

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/linux/LibC.java
contrib/platform/src/com/sun/jna/platform/linux/package.html
contrib/platform/test/com/sun/jna/platform/linux/LibCTest.java

Not sure if it's appropriate to put linux under unix. Could incur the wrath of GNU. :)

Add Linux LibC with sysinfo

---

build.xml
test/com/sun/jna/TypeMapperTest.java

The codepath in the structure creation causes NULL to be passed to
`TypeConverter#toNative`. This needs to be handled to be able to use
enums in Structures.

Improve test for using TypeMapper with Enums

---

contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java

This is only removing obviously unnecessary assignments in `Advapi32Util`.

Remove redundant assignments in Advapi32Util

---

CHANGES.md
contrib/platform/build.xml
src/com/sun/jna/Native.java
src/com/sun/jna/overview.html
test/com/sun/jna/JNALoadTest.java

Two problems are addressed here:
1. it is a long standing issue, that JNA should default to not load the `jnidispatch` library from the system search path. This was again observed when introducing appveyor builds, as there somehow a jnidispatch library is on the system path
2. Unix systems (Mac OS X and Linux at least) default to a global system temp directory. This is unsafe, as an attacker could gain control over that directory. This is nor fixed.

Optimize library loading

---

contrib/platform/src/com/sun/jna/platform/win32/COM/COMBindingBaseObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMEarlyBindingObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/COMLateBindingObject.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/Variant.java

This prepares for API cleanup in JNA 6, where the now
deprecated methods will be removed and the 
COM*Binding objects will be rebased onto Dispatch.

COM Cleanup Part 1

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Secur32.java
contrib/platform/test/com/sun/jna/platform/win32/Secur32Test.java

In the unittests the case, where the call to this method would have been
necessary, was not reachable. Therefore no new unittest for this
function was added.

Bind `c.s.j.p.win32.Secur32#CompleteAuthToken`

---

CHANGES.md
build.xml
src/com/sun/jna/Native.java

Android only supports loading libraries through the JVM `System#loadLibrary`
mechanism, defaulting `jna.nosys` to `true` disabled that code path.

Fix loading jnidispatch on android

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/WindowUtils.java
contrib/platform/test/com/sun/jna/platform/win32/WindowUtilsTest.java

[GITHUB-1042] c.s.j.p.WindowUtils.W32WindowUtils.getProcessFilePath does not close process handle

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/PdhUtil.java

While the fix in #1052 worked on one XP system it did not work on another. Not sure if it was character encoding or bitness or something else, but [the docs](https://docs.microsoft.com/en-us/windows/desktop/api/pdh/nf-pdh-pdhlookupperfnamebyindexa) were also unclear as to the behavior of the buffer length value:
> The function sets pcchNameBufferSize to either the required size or the size of the buffer that was used.
And also suggesting error code response varied:
> PDH_INVALID_ARGUMENT ... on some releases you could receive this error if the specified size on input is greater than zero but less than the required size.
This second fix should work and passes tests on a few different XP VMs.  Vista+ does the "pass null, get size, get result" calls.  For XP the buffer is incremented until …

WinXP Compatibility for PdhUtil#PdhLookupPerfNameByIndex

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/VersionHelpers.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/VersionHelpersTest.java

See [reference docs](https://docs.microsoft.com/en-us/windows/desktop/SysInfo/version-helper-apis).  Code directly adapted from [header file here](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/um/VersionHelpers.h).

Add Windows Version Helper functions

---

CHANGES.md
src/com/sun/jna/Native.java

It seems System#mapLibraryName from OpenJDK works differently on AIX
than J9. J9 expands jnidispatch to libjnidispatch.a, while OpenJDK expands
it to libjnidispatch.so. This in turn causes the loader to search for the wrong file.
https://github.com/java-native-access/jna/issues/1066
Closes: #1066

Use correct native library on OpenJDK on AIX

---

CHANGES.md
src/com/sun/jna/Native.java

Fixes https://github.com/java-native-access/jna/issues/1079

Fix maximum structure alignment on Android i386

---

CHANGES.md
src/com/sun/jna/internal/ReflectionUtils.java

`c.s.j.internal.ReflectionUtils` accesses `java.lang.invoke.MethodType`
without reflection, causing `java.lang.NoClassDefFoundError`
on android API level < 26
MethodType is already accessed via reflection and just for the method
lookup the class literal was used. The literal use was removed and
replaced with the class already looked up via reflection.
Closes: #1089

[GITHUB-1089] Fix missing reflection use in `c.s.j.internal.ReflectionUtils`

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/src/com/sun/jna/platform/win32/Netapi32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/Netapi32Test.java

As a performance optimization calls to Collections#toArray where changed
from providing a correctly sized array to using a zero sized array.
See 07f3ce053d947adadf80a20e8acf8caffca8b6cd
The change is invalid if the object toArray is called on is a Structure,
the calls just look the same. This changeset is a partial revert of the
above mentioned commit.
Closes: #1087

[GITHUB-1087] Fix wrong calls to Structure#toArray with zero sized arrays

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java

The terms "Event ID" and "event identifier" refer to different things, which leads to confusion and probably led to .NET deprecating the former term. JNA should do the same.

Deprecate EventLogRecord#getEventId in favor of #getInstanceId

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

[GITHUB-1115] Fix c.s.j.p.win32.Kernel32#CreateRemoteThread and bind VirtualAllocEx, VirtualFreeEx, GetExitCodeThread

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/IShellFolder.java
contrib/platform/test/com/sun/jna/platform/win32/COM/IShellFolderTest.java

IShellFolder#ParseDisplayName third argument requires a null-terminated wide string in Windows but is mapped as a String.    Initial commit is failing testcase.

Windows expects Unicode String for IShellFolder#ParseDisplayName

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinBase.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Per [MSDN docs](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info), the `dwOemID` member of the `SYSTEM_INFO.processorArchitecture` union is obsolete.  The correct `pi` member of the union is a structure and isn't read by default. This change sets the type so the structure can be read.  Fixes #1057

Force read of processorArchitecture member of SYSTEM_INFO union

---

CHANGES.md
native/testlib.c
src/com/sun/jna/Native.java
src/com/sun/jna/Structure.java
test/com/sun/jna/ArgumentsMarshalTest.java
test/com/sun/jna/DirectArgumentsMarshalTest.java
test/com/sun/jna/PerformanceTest.java
test/com/sun/jna/StructureTest.java
test/com/sun/jna/UnionTest.java

System V x86-64 ABI requires, that in a union aggregate, that contains
Integer and Double members, the parameters must be passed in the integer
registers. I.e. in the case where the java side declares double and int
members, the wrong FFI Type would be found, because the doubles size is
larger than the int member, but the wrong parameter passing method would
be used.

 [GITHUB-1118] Ensure union with floating point and integer member is passed in integer register

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/mac/SystemB.java
contrib/platform/test/com/sun/jna/platform/mac/SystemBTest.java

On macOS, the `System` framework includes the C library headers (`libc`) so it is appropriate to extend the `LibCAPI` class rather than duplicating Unix method mappings.

SystemB extends LibCAPI

---

build.xml

This PR updates the build of the JNA OSGi bundle to support an additional processor architecture to allow the bundle to be installed on OSGi running on Raspberry Pi 3 B+ with a 32bit OS.
Apache Felix's OSGi implementation reports the `osgi.native.processor` as either `arm_le` or `arm_be` when the system property `os.arch` returns `arm`.
When running a 32bit OS on the RPi Java reports `arm` for `os.arch` which is normalized to `arm_le` by Felix. Because of this, the JNA bundle cannot be installed since this architecture is not currently listed in the OSGi `Bundle-NativeCode` header. When attempting to start the bundle you get the following error:
```
Error executing command: Error executing command on bundles:
Error starting bundle 13: Unable to resolve com.sun.jna [13](R 13.0): missing …
```

Update OSGi headers for the JNA bundle to support 32bit ARM on Raspberry Pi 3 B+

---

.travis.yml

`contrib` projects that use `javac` target/source = 1.6 no longer compile on jdk 13 on mac osx. 
This PR attempts to update the CI config to use jdk11 on the mac OS X build to allow an older javac target/source value (1.6) in the contrib tree. Using jdk11 instead of 12 because 11 is still maintained.
A different solution (updating `contrib` to target/source = 1.7)  is presented in PR #1163

Mac osx build to use jdk11 for 1.6 compatibility

---

www/RaspberryPiDevelopmentEnvironment.md

I saw a build failure that appears to be caused by missing `makeinfo`, and fixed by installing the `texinfo` package.

document need for texinfo package to build on raspberrypi

---

src/com/sun/jna/NativeLibrary.java

Whilst debugging #1175 , I noticed that the search paths contained duplicate paths (in my case, `/usr/lib`). These two patches change the variables that hold the paths to `LinkedHashSet` as it both preserves the insertion order and prevents duplicate entries.

Prevent duplicates in library paths

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java

`Pointer#getChar` fetches two bytes but this is a one-byte `IntegerType`.
[See mailing list](https://groups.google.com/forum/#!topic/jna-users/XaRVbHM9le8).

CHARByReference#getValue should only read one byte

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinDef.java

Although this is a Windows types and the existing calculation always works on Windows, there's no reason calculate it based on `LONG` size.

ULONGLONG should always be 8 bytes

---

contrib/platform/test/com/sun/jna/platform/linux/LibCTest.java

Instead of iterating mountpoints only query the information of the root directory and use NIO to query the java comparison data.

Fix statvfs filesystem - it is unstable in docker environments

---

contrib/platform/test/com/sun/jna/platform/win32/IPHlpAPITest.java

The established connections is a current value, while reset connections is a cumulative total.  Also made test errors more verbose.

Remove invalid GetTcpStatistics test

---

.travis.yml

As of 2020-05-13, there are two versions of Apache Ant 1.9.x binaries available for download.  The regexp parsing incorrectly resolves to a string containing both versions, separated by a newline character, and the download fails.   This change limits the grep to only the last line, so the latest 1.9.x version will be downloaded.

Only fetch the latest ant version in Travis script

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32UtilTest.java

The current Advapi32Util#getTokenGroups method can incur significant latency, 20-45 seconds on my corporate machine.  Only asking for the primary group is on the order of 20-45 milliseconds.

Add getTokenPrimaryGroup to Advapi32Util

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/test/com/sun/jna/platform/win32/WinNTTypesTest.java

As discussed on the mailing list.   Initial commit is a failing test case.

LARGE_INTEGER needs to populate both union fields

---

.travis.yml

Added arm64 support to .travis.yml file.
1.  JDK 11 is used to build jna on arm64. Thus, "openjdk-11-jdk" will be installed and JAVA_HOME and PATH will be set according to that.
2. libltdl-dev package needs to be installed for supporting arm64.

Added arm64 support to .travis.yml file

---

contrib/platform/test/com/sun/jna/platform/linux/LibCTest.java

The test that usable space equals available space on a filestore is too strict, as it can fail in a race condition between fetching `statvfs` and getting the same information from core Java: 
```
assertEquals(fstore.getUsableSpace(), vfs.f_bavail.longValue() * vfs.f_bsize.longValue());
```
[Failed test](https://travis-ci.org/github/java-native-access/jna/jobs/691071994):
```
[junit] Testcase: testStatvfs(com.sun.jna.platform.linux.LibCTest):	FAILED
[junit] expected:<816184561664> but was:<816175988736>
```
In theory we could test for something "close" but any change threshold we choose would be arbitrary.  Given the previous line checks equality of total space, which should not change, I think this test can simply be removed.

Remove too-strict filestore available size test

---

src/com/sun/jna/NativeLibrary.java
test/com/sun/jna/NativeLibraryTest.java

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)
Fix #1215.
Signed-off-by: David Kocher <dkocher@iterate.ch>

Try all frameworks paths regardless of file exist check.

---

contrib/platform/src/com/sun/jna/platform/win32/Tlhelp32.java

Field members were not declared public in #1209. I likely found and fixed this locally and forgot to push the fix upstream.

Fix THREADENTRY32 field visibility bug

---

CHANGES.md
contrib/platform/build.xml

Passing -Dw32.ascii=true or -Dw32.ascii=false on the command line to ANT
will forward the property to the test suite. This allows to run tests on
both the ANSI and the UNICODE versions of the API explicitly.
Not passing the -Dw32.ascii command line option results in the same
behavior as previous versions, i.e. the property is not set.
Signed-off-by: Torbjörn Svensson <azoff@svenskalinuxforeningen.se>

Allow overriding w32.ascii when running test suite

---

contrib/platform/test/com/sun/jna/platform/win32/User32WindowMessagesTest.java

Commit 7372ba5 introduced return type checking for calls. This is
invalid for the case of EnumWindow. The callback passed to EnumWindow
(EnumWindowsProc) is documented as:
To continue enumeration, the callback function must return TRUE; to
stop enumeration, it must return FALSE.
And EnumWindow:
If EnumWindowsProc returns zero, the return value is also zero. In
this case, the callback function should call SetLastError to obtain a
meaningful error code to be returned to the caller of EnumWindows.
TL;DR: If the iteration is ended early (as is the case here if the
target HWND is found), the return is 0 and thus FALSE.

Fix broken unittests by 7372ba5

---

contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java

Two small improvements related to code related to Variants:
- Convert.toJavaObject: Reduced the number of VARIANT.getVarType calls
- ProxyObject.setProperty: Avoid creation of not used Variant instance
See commit messages for details about the changes.

Minor improvements to code related to Variants

---

src/com/sun/jna/Memory.java

The Memory.allocatedMemory Map had a unused WeakReference as value,
only the key is used to work with the Memory instance. Replacing the
value will reduce the overhead for each Memory instance.

Replaced unused WeakReference with Boolean in Memory.allocatedMemory

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/test/com/sun/jna/platform/win32/User32WindowMessagesTest.java

Method documentation: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-callwindowproca
First time contributing here, not sure what a test for this method would look like so any pointers would be appreciated ^^

Add CallWindowProc to User32

---

CHANGES.md
native/Makefile

Since GCC 10 warnings for unbounded alloca calls are turned on by
default. The size of the allocation comes from the java side of the
bindings and thus appears to be unchecked on the native side.

Fix build error on GCC 10 caused by alloca bound warnings

---

CHANGES.md
src/com/sun/jna/Structure.java

Reduced the number of Set lookups in Structure.read / Structure.write.
Introduced a new class to replace two entries of a HashMap with one.
This reduces the number of lookups and the initial capacity has been
reduced too.
There is one additional change in line ~363 to avoid a Memory.share() 
call if the size of the structure is known.
I could create a benchmark if required.

Optimized Map/Set lookups in Structure

---

src/com/sun/jna/CallbackReference.java

WeakHashMap is not threadsave and concurrent access can lead to
undefined behaviour. Infinite loops were observed in in the wild.

Protect concurrent access to CallbackReference#allocations by multiple threads

---

contrib/platform/src/com/sun/jna/platform/win32/Variant.java

The VariantArg#ByReference(VARIANT[]) constructor did not call the
correct super overloading. This change will avoid the creation of an
not needed array by the VariantArg#ByReference(VARIANT[]) constructor.

Fixed a broken super() call

---

src/com/sun/jna/Structure.java

Dropped the reflective read of the currently written field value from Structure.writeField(String name, Object value). This improves performance of explicit writeField calls, usally done if autoWrite is disabled for performance reasons.

Avoid reading the currently written field

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Crypt32.java
contrib/platform/src/com/sun/jna/platform/win32/WinCrypt.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32Test.java

The implementations of the rgAttribute, rgCTLEntry and rgExtension
attributes are not in line with the observed behaviour of the API. At
least in part they are documented to be pointers to arrays of pointers
to structures. This is not correct, as segfaults were observed and
testing shows, that they are in fact pointers to arrays of structures.
In addition it was observed, that the bindings of CTL_INFO#getRgCTLEntry
and CTL_INFO#getRgExtension method names were inverted.
The bindings for CERT_EXTENSIONS#getRgExtension and 
CTL_INFO#getRgExtension are untested as but assumed to be implemented
identically to the tested bindings.
The functions 
- CertEnumCertificatesInStore
- CertEnumCTLsInStore
- CertEnumCRLsInStore
- CryptQueryObject
from `c.s.j.p.win32.Crypt32` were bound to be able to …

Enhance bindings for Crypt32 and fix bindings for array attributes

---

.gitattributes

Force automake files to use `eol=lf` on clone, avoiding the [painstaking `dos2unix` workarounds](https://github.com/java-native-access/jna/blame/3996d47ef55c2ab99834ef9817a989c87d8a85ee/www/WindowsDevelopmentEnvironment.md#L55).
Related #1264, since the request may lead to a modification of `www/WindowsDevelopmentEnvironment.md` for ARM64 support, which specifically mentions:
> If you get errors such as `'\r': command not found`, run `dos2unix -f [filename]` for each file that it's complaining about.
In my experience, the error is much more vague and obscure, e.g. `AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4` (and dozens of other confusing automake-generated errors) sending developers on a wild goose chase. 🍻 
Another alternative is to set the following:
```bash
git …
```

Remove the need for dos2unix

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/mac/CoreFoundation.java
contrib/platform/test/com/sun/jna/platform/mac/CoreFoundationTest.java

If you try to convert a CFStringRef with empty string (char[0]) an Exception is throws in com.sun.jna.Memory(long) constructor:
java.lang.IllegalArgumentException: Allocation size must be greater than zero
Issue: https://github.com/java-native-access/jna/issues/1274

Fix native conversion for empty CFStringRef.

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/WindowUtils.java
contrib/platform/src/com/sun/jna/platform/win32/Psapi.java
contrib/platform/src/com/sun/jna/platform/win32/PsapiUtil.java
contrib/platform/test/com/sun/jna/platform/mac/XAttrUtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/User32WindowMessagesTest.java

With the improvements done by @tresf in #1264 three failing windows unittests on x86 were identified:
- `GetModuleFileNameExW` can fail on 64bit platforms, if the calling programm is 32bit. I did not find official documentation about this, but the indication I found on the net speculate, that the problem is observed, when the target process is mapped beyon the memory range, that a 32 bit process can observe. `GetProcessImageFileName` can be used as an alternative, but returns a different format (device path) and needs to be converted, to return the expected value.
- `testCreateRemoteThread` creates a thread by writing the binary directly into memory and starting the thread with the memory location. That binary was only valid for 64bit, but nor for 32 bit (different calling convention). …

Fix unittests for windows 32bit intel

---

CHANGES.md
src/com/sun/jna/CallbackReference.java
test/com/sun/jna/CallbacksTest.java

Regarding https://github.com/java-native-access/jna/issues/326,
Changes are the following:
- map of pointer-to-callback is replaced with a map of pointer-to-array-of-callbacks to handle callbacks with different signatures mapped to the same native pointer.
- modified related unit test
Not sure if this was the best solution, I hope that you can give me feedback on it.
I did not benchmark it.

Pointer already mapped

---

CHANGES.md
contrib/native_window_msg/build.xml
contrib/native_window_msg/src/com/sun/jna/platform/win32/Win32WindowDemo.java
contrib/platform/src/com/sun/jna/platform/win32/DBT.java
contrib/platform/test/com/sun/jna/platform/win32/DBTTest.java

- Ensure all structures defined in com.sun.jna.platform.win32.DBT can be
instantiated
- Use correct mapping for DEV_BROADCAST_PORT#dbcp_name. And add accessor
for the string value of that property. This is an API incompatible
change, but the class could not be instantiated, so it is assumed,
that it is a safe change
- Prevent potential out-of-bounds read in DEV_BROADCAST_DEVICEINTERFACE
- Make demo-nativewindowmsg.jar runnable
Closes: #1286

[GITHUB-1286] Fix DBT Bindings and Win32WindowDemo

---

.github/workflows/ci.yaml
.travis.yml
README.md

As noted in #1282 sometime in the next few weeks, travis-ci.org will go away and accounts will be migrated to travis-ci.com.
While Travis CI has announced that they will still permit free builds for open source projects, they require a manual allocation of CI minutes (after an initial free 1000 minutes).  To reduce the rate at which we use these minutes, I've removed builds which have already been migrated to Github Actions. Presently that leaves only the Linux ARM build on Travis.

Reduce Travis CI Build Matrix

---

contrib/platform/src/com/sun/jna/platform/win32/WinspoolUtil.java

Closes GH-1289.
Fix `ArrayIndexOutOfBoundsException` if printer job is completed before `Winspool.INSTANCE.EnumJobs` is called second time.
Not sure how to cover this in unit tests, any ideas are welcome :-)

GH-1289: Fix `ArrayIndexOutOfBoundsException`

---

contrib/monitordemo/build.xml
contrib/platform/src/com/sun/jna/platform/win32/Winspool.java
contrib/w32printing/build.xml
contrib/w32printing/src/com/sun/jna/platform/win32/Win32SpoolMonitor.java

Adds in the Java mappings for a number of structures required to
allow specifying complex options to `Winspool`s notification APIs.
Shout out to @matthiasblaesing for helping to fix the function
definitions - more info here:
https://groups.google.com/g/jna-users/c/FpWPY2c8bzY

[Win32] Add support for options in Winspool notifications API

---

native/build.xml

I think this will fix the build failure that occurred recently in the JNA-maven build. Was missing some ant namespace stuff to enable nifty new things.

fix native compile error due to use of ant if,unless

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WTypes.java
contrib/platform/test/com/sun/jna/platform/ByReferencePlatformToStringTest.java

Fixes #1292 
As noted in the issue, this is already tested for in `c.s.j.p.ByReferencePlatformToStringTest`.  I used the gc-based test code noted in the issue (and a few hundred instantiations in an array) to reproduce the issue at will before the fix and confirm this fixes that problem.  I also added null checks.
This does not protect against all cases, just the two most obvious ones (not throwing exceptions on null and tracking memory when  a `BSTR` constructor is used).  
An alternative solution would be to deprecate the `BSTR` constructor and replace it with a `Pointer` constructor, making much more clear to the user what is being stored. I think I prefer this (deprecate) alternative but wanted to at least see what it would take to fix the existing one and get feedback.

Deprecate BSTR String constructor and setValue method

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/IPHlpAPI.java
contrib/platform/test/com/sun/jna/platform/win32/IPHlpAPITest.java

Also added some of the supporting structures sufficient to replicate most of `netstat` output for TCP and UDP.

Add IpHlpApi GetExtendedTcpTable and GetExtendedUdpTable

---

contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Fix Kernel32Test#testSetErrorMode with stuck alignment error bit

---

README.md
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/IPHlpAPITest.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
contrib/platform/test/com/sun/jna/platform/win32/SAFEARRAYTest.java

I tried to get windows tests running on Github Actions.  I've fixed some of the failures that I identified but there are still several failures in Advapi32 and Advapi32Util test classes that I can't seem to fix, and can't figure out how to suppress in ant using test excludes.
Committing the fixes for now.

Fix some windows test failures

---

CHANGES.md
build.xml
pom-jna-jpms.xml
pom-jna-platform-jpms.xml

The jna-platform artifact depends on jna - this leads to problems when
the JPMS artifacts are used, as the pom.xml for the classifier based
artifacts are identical to the base artifacts. This leads to
```xml
<dependency>
<groupId>net.java.dev.jna</groupId>
<artifactId>jna-platform</artifactId>
<version>5.7.0</version>
<classifier>jpms</classifier>
</dependency>
```
depending on
```xml
<dependency>
<groupId>net.java.dev.jna</groupId>
<artifactId>jna</artifactId>
<version>5.7.0</version>
</dependency>
```
so the jna-platform JPMS artifacts pulls in the non-JPMS jna artifact.
To solve this, both artifacts are moved into their own groupId. So
```xml
<dependency>
<groupId>net.java.dev.jna</groupId>
<artifactId>jna-platform</artifactId>
<version>5.8.0</version>
<classifier>jpms</classifier> …
```

Split jpms modules into independet artifacts instead of classifier based solution

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java

In rare/transient situations, such as UAC elevation or other SYSTEM account situations, the domain name can be an empty string. In this case `cchDomainName` is set to 0 and a zero-length array causes the function call to fail with an incorrect parameter.  See https://github.com/oshi/oshi/issues/1551 and https://github.com/oshi/oshi/issues/637 for examples of failure symptoms.
Rather than adding code to handle the special case, we can simplify the code to avoid the initial call to get length, and prevent this error by using the max possible string lengths.  
[`GetUserName`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getusernamea) docs indicate:
>  A buffer size of (UNLEN + 1) characters will hold the maximum length user name including the terminating null …

Handle 0-length domain names in Advapi32Util#getAccountBySid

---

.gitignore
CHANGES.md
nbproject/ide-file-targets.xml
nbproject/project.xml
src/com/sun/jna/Memory.java
test/com/sun/jna/MemoryTest.java

The use case is this:
- native supplies the required size of a memory region
- a Memory object is created with the right memory size
- native fills the memory with a structure _and_ additional objects,
that are held in that region, but are only referenced from the
structure (one such example would be a Structure.ByReference)
As long as the resulting structure stays strongly referenced from Java,
all is good. When the toplevel structure goes ouf of scope, the memory
backing the strucure is not strongly referenced anymore and will be
freeed by GC.
This change fixes the issue by ensuring, that the pointers used in
substructures are SharedMemory objects, holding a strong references to
the original Memory object.

 Ensure pointers indirected from Memory and pointing into Memory should retain originating object

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java

See #1324 for more details.
This PR implements new `LOGICAL_PROCESSOR_RELATIONSHIP` enum values which are present in current Windows Insider builds and currently throw an `IllegalStateException` when instantiating a `SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX` structure from a pointer.
A complete implementation will require updating the `NUMA_NODE_RELATIONSHIP` structure and javadocs, and will be submitted later once the new API documentation is available.

Add partial support for future values of LOGICAL_PROCESSOR_RELATIONSHIP

---

.travis.yml

The HTML for the `ant` binaries now repeats the file name in a title field which breaks version parsing, resulting in
> apache-ant-1.9.15-bin.tar.gz" title="apache-ant-1.9.15
Ensuring that the regex capture ends at a quotation mark (ending the href field) properly parses the version.
> apache-ant-1.9.15

Fix parsing of ant version in Travis script

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/mac/CoreFoundation.java
contrib/platform/test/com/sun/jna/platform/mac/CoreFoundationTest.java

Fixes #1342 (again)
macOS incorrectly uses a 3 byte per character conversion when determining the maximum byte size of a UTF8 encoded string.  Changing the buffer size calculation to use 4 bytes (plus a null byte) actually produces an appropriately sized buffer.

CFStringRef#stringValue buffer needs space for 4 UTF8 bytes

---

contrib/platform/build.xml
www/FrequentlyAskedQuestions.md

Because `jna-platform` exposes classes from the `java.awt` package in its API, downstream dependencies should have implied readability to `java.desktop` using `requires transitive` so users don't have to discover this later and include it in their own module descriptor.  Similarly, `java.awt.datatransfer` classes are also exposed so `java.datatransfer` should also be required transitively.
While it is probably good practice from a Maven dependency resolution perspective to also include the same version of `jna-jpms`, that should be an option by permitting the same implied readability of classes in the `com.sun.jna` module.
I've also updated the FAQ referencing the new 5.8.0 setup.  I considered mentioning the classifiers in 5.7.0, but there should be no need for anyone to use an older …

Add transitive requires and update FAQ

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/mac/CoreFoundation.java
contrib/platform/test/com/sun/jna/platform/mac/CoreFoundationTest.java

The code fix from #1343 was correct.  I reverted the change in #1345, added more comments to clarify what is happening, and added tests for 1-, 2-, 3-, and 4-byte UTF8 characters.
Java uses one `char` for Unicode code points under 0xffff and two chars (with a leading [high-surrogate code unit](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isHighSurrogate-char-)) for code points 0x10000 and higher, which correspond to the same number of "UTF-16 characters" in the Apple docs.

Revert #1345, clarify comments and add tests

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/mac/SystemB.java
contrib/platform/src/com/sun/jna/platform/unix/LibCAPI.java
contrib/platform/test/com/sun/jna/platform/ByReferencePlatformToStringTest.java
contrib/platform/test/com/sun/jna/platform/mac/SystemBTest.java

This fixes the types in `SystemB`.
I added a `ByReference` nested class to the existing `size_t` type already mapped in a superclass, to handle the conditional buffer allocation similarly to `NativeLongByReference`.

Define size_t.ByReference and fix macOS sysctl size_t* parameters

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java

Method documentation: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-bringwindowtotop

Add `BringWindowToTop` to `c.s.j.p.win32.User32`

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/User32.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java

MSDN documentation for `GetParent`: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getparent

Add `GetParent` to `c.s.j.p.win32.User32`

---

pom-jna-jpms.xml
pom-jna-platform-jpms.xml
pom-jna-platform.xml
pom-jna.xml

- the maven pom.xml documentation recommends to use the SPDX identifier
as license name
- the link to the LGPL 2.1 license should point to license itself, not
to an overview page (reported by @TorstenKruse)
Closes: #1355

Optimize license information in pom.xml

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Shell32.java
contrib/platform/src/com/sun/jna/platform/win32/Shell32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Shell32Test.java
contrib/platform/test/com/sun/jna/platform/win32/Shell32UtilTest.java

API reference: https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw

Add CommandLineToArgvW to Shell32 and corresponding util

---

test/com/sun/jna/VMCrashProtectionTest.java

Just noticed the issue in `VMCrashProtectionTest`.
The code below never fails because the `AssertionFailedError` is swallowed in the catch block (which seems intended for an exception from `setInt` method).
```
try {
p.setInt(0, 0);
fail("Exception should be thrown");
}
catch(Throwable e) {
}
```
Most likely that in case of VM crash the execution will never reach the line with `fail(...)` call, so any attempt to do "the right thing" here is unnecessary. But anyway I believe the original code with the `fail(...)` call is more confusing than the code that checks thrown exceptions properly or at least comment that explains why it's not necessary checks thrown exceptions.

checked properly that exception is thrown

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Crypt32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32UtilClearSecuritySensitiveDataTest.java

#1362 Crypt32Util.cryptProtectData leaves security sensitive information in memory
https://github.com/java-native-access/jna/issues/1362

cleaned security sensitive data after usage

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinCrypt.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32UtilTest.java

Allocated 1-byte array in case when 0-length array is supplied in order to avoid IllegalArgumentException
Generally speaking `LocalAlloc` accepts size=0, by `malloc` (which is used in this place) may return `null` in this case, which is indistinguishable from OOM condition.

Crypt32Util.cryptProtectData fails on zero-length array

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java

See background in #1324.
API Reference: https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-numa_node_relationship
Mapping directly to the API union loses backwards compatibility. This version populates the variable sized array of the newer union, and copies that value to a backwards-compatible field that is accessible to users but excluded from the Structure's field lists.

Update NUMA_NODE_RELATIONSHIP to new variable size structure

---

contrib/platform/src/com/sun/jna/platform/win32/COM/COMLateBindingObject.java
contrib/platform/test/com/sun/jna/platform/win32/COM/ComEventCallbacks_Test.java
contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java
contrib/platform/test/com/sun/jna/platform/win32/SAFEARRAYTest.java

Reviewed all internal allocations of `BSTR` (as `VARIANT`) and `SAFEARRAY`.  Added code to free the allocations when possible.  While these are test methods, and one was clearly intentional, it's better to correctly free; users sometimes use tests methods as examples.
The `COMLateBindingObject.setProperty(String propertyName, String value)` method allocates a `BSTR` which becomes inaccessible to the user.   Its implementation eventually reaches a deprecated method, and probably should be considered for deprecation:
- setProperty(String propertyName, String value)
- oleMethod(int nType, VARIANT.ByReference pvResult, String name, VARIANT pArg)
- oleMethod(int nType, VARIANT.ByReference pvResult, String name, VARIANT[] pArgs)
- (deprecated) oleMethod(int nType, VARIANT.ByReference pvResult, …

Free BSTR and SAFEARRAY allocations when done

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Advapi32.java
contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32UtilTest.java
contrib/platform/test/com/sun/jna/platform/win32/Crypt32Test.java

Also, fix source compatibility with Java 6. It blocks my local test run.

Add RegLoadAppKeyW 

---

CHANGES.md
native/dispatch.c

`ffi_closure_alloc` may fail and return `NULL` if, for instance, we're
running in a locked-down operating system that forbids FFI from
allocating executable pages of memory in any of the ways that it tries.
Today we pass this `NULL` on to `ffi_prep_closure_loc` which triggers a
segmentation fault that takes down the whole JVM. With this change we
check for a failure in this call and turn it into an
`UnsupportedOperationException` so that the caller can handle it more
gracefully.
Relates elastic/elasticsearch#73309
Relates elastic/elasticsearch#18272
Closes #1107

Handle failure in `ffi_closure_alloc`

---

.github/workflows/ci.yaml
.gitignore
CHANGES.md
build.xml
contrib/alphamaskdemo/build.xml
contrib/balloonmanagerdemo/build.xml
contrib/balloontips/build.xml
contrib/dnddemo/build.xml
contrib/monitordemo/build.xml
contrib/msoffice/build.xml
contrib/native_window_msg/build.xml
contrib/shapedwindowdemo/build.xml
contrib/w32printing/build.xml
contrib/w32windowhooks/build.xml
contrib/x11/build.xml
src/com/sun/jna/Native.java

JEP 400 will make UTF-8 the default value for `file.encoding` for java:
https://openjdk.java.net/jeps/400
For JNA this means on windows (on mac OS and Linux the encoding for native can be expected to be UTF-8 already) the native codepage would not be used anymore.
See the comments of the first commit for an explanation how it will be reworked.

Update native encoding detection for JEP400

---

contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Advapi32Test.java
contrib/platform/test/com/sun/jna/platform/win32/NtDllTest.java
contrib/platform/test/com/sun/jna/platform/win32/SetupApiTest.java

`WinBase.INVALID_HANDLE_VALUE` is a pointer to the value -1.  In several places, object (reference) equality is ~incorrectly~ used to test return values, ~which are likely a different pointer to -1~ is confusing to those who don't know the internal implementation forcing these equalities.

Improve clarity of equality tests for INVALID_HANDLE_VALUE

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Sspi.java

Fixes #1396. See also #291.
Alternately, we could read the `MaxTokenSize` registry entry value at `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\Kerberos\Parameters` if it exists, and default to these values otherwise, but that's way too complex to put in an initialization.

Increase Sspi#MAX_TOKEN_SIZE on Windows 8/Server 2012 and later

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32Util.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32UtilTest.java

Fixes #1410
Apparently what the caller in such a situation expects is to get the content of the *existing* section, i. e. an empty String array.
Using a constant object to reduce heap pollution.

Do not throw Win32Exception on success for empty section in Kernel32Util#getPrivateProfileSection

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/solaris/Kstat2.java
contrib/platform/src/com/sun/jna/platform/unix/solaris/Kstat2StatusException.java
contrib/platform/test/com/sun/jna/platform/unix/solaris/Kstat2Test.java

The Kstat library is deprecated beginning in Solaris 11.4, replaced by Kstat2.
Docs here:  https://docs.oracle.com/cd/E88353_01/html/E37846/kstat2-3kstat2.html
Implemented here:  https://github.com/oshi/oshi/pull/1837

Add Solaris Kstat2 Library

---

contrib/platform/test/com/sun/jna/platform/mac/IOKitTest.java

Fixes test failure reported in #1419

Fix IOKitTest for M1 compatibility

---

CHANGES.md
appveyor.yml
contrib/platform/test/com/sun/jna/platform/mac/IOKitTest.java
native/callback.c

libffi requires the number of fixed arguments to an ffi call to be
correctly provided. For the callback case the conversion routine
supplied the wrong number of arguments for the dispatch into java.
The JNI callbacks have the signature:
NativeType Call<type>Method(JNIEnv *env, jobject obj, jmethodID methodID, ...);
so the first three arguments are fixed and the rest is passed as
varargs.
Closes: #1323

Fix crash in direct callbacks on mac OS aarch64

---

CHANGES.md
native/dispatch.c

At least Ubuntu builds the JDK with RUNPATH set instead of RPATH. The
two differ in their effect on loading transitive dependencies.
RPATHs effect also covers libraries loaded as transitive dependencies,
while RUNPATH does not. In the case of JNA libjawt is loaded by
libdispatch (the native JNA part), which makes it a transtive load.
The solution is to load the library with the full path based on the
sun.boot.library.path system property, which points to the native
library dirs.

Load jawt library relative to sun.boot.library.path system on unix OSes

---

CHANGES.md
native/testlib.c
src/com/sun/jna/Structure.java
test/com/sun/jna/DirectStructureByValueTest.java
test/com/sun/jna/StructureByValueTest.java

libffi uses ffi_type structures to describe arrays and structures passed
to native. JNA builds these structures and caches them using the
associated classes as keys. For arrays this leads to the situation where
only a single ffi_type was stored for all sizes of the same base type.
This in turn causes wrong behavior in libffi.

Handle arrays in structures with differing size

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/PdhUtil.java

`PdhException` can occur when fetching lists of counter instances which change frequently, such as processes or threads.

Handle race condition in PdhUtil#PdhEnumObjectItems

---

src/com/sun/jna/internal/Cleaner.java

This assumes that InterruptedException is only raised when the JVM is shutting down.

Don't log exception if cleaner thread is interrupted

---

www/Contributing.md

Attempt to define some semblance of consistency for new committers.  Relates to #1458.
Signed-off-by: Daniel Widdis <widdis@gmail.com>

Update contribution guidelines

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java
src/com/sun/jna/Pointer.java
test/com/sun/jna/PointerTest.java

Fixes #1470 
`Pointer#hashCode`: defined the mask properly to show author intent, although one could just as easily add without masking because of the eventual downcast.
`ProxyObject#hashCode`: this one had an additional useless mask of a number already shifted right 32 bits and guaranteed to have 0's in the high bits. And in addition to the useless mask of the low bits  it then gets downcast to int and then widened again for the addition.  Simplified it to match the Pointer version.
`Pointer#createConstant(int)` states in its javadocs that it is supposed to avoid setting the high bits.  However, with the improper masking it ends up setting all the high bits for any negative ints.

Fix incorrect bitmask in Pointer#createConstant(int)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/Wbemcli.java
contrib/platform/test/com/sun/jna/platform/win32/COM/WbemcliTest.java

Added methods to IWbemContext, IWbemServices and IWbemClassObject. Added IWbemQualifierSet.

Added WBEM methods and a class.

---

CHANGES.md
src/com/sun/jna/Library.java
src/com/sun/jna/NativeLibrary.java
src/com/sun/jna/SymbolProvider.java
test/com/sun/jna/NativeCustomSymbolProviderTest.java

Retake on https://github.com/java-native-access/jna/pull/1483 I'm using a different branch, since I used master and that was problematic for syncing the original repo. I have also squashed all the commits into one.
---
This allows to do function hooking/replacement while still using [direct mapping](https://github.com/java-native-access/jna/blob/master/www/DirectMapping.md).
In addition to that, to properly using the OpenGL library on Windows, and access OpenGL >= 2.0, we need to use a custom `getSymbol` function: https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglgetprocaddress
In the test I'm switching `cos` and `sin` functions to show it works.
---
Started a thread here: https://groups.google.com/g/jna-users/c/RDt8sHAnTm0

Adds support for a custom SymbolProvider in NativeLibrary & Library

---

test/com/sun/jna/NativeLibraryTest.java

This test basicly tests whether unloading works. It relies on the runtime to unload the library when dlclose is called. This is not required by POSIX and dt time of writing macOS is known to be flaky in that regard.
This test causes false test failures.
Closes: #1423

Disable NativeLibraryTest#testAvoidDumplicateLoads

---

.github/workflows/ci.yaml

Closes #1507 
- set ci.yaml permissions to `contents: read`

chore: set ci.yaml permissions.

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/COM/Wbemcli.java
contrib/platform/test/com/sun/jna/platform/win32/COM/WbemcliTest.java

Added additional functions to IWbemClassObject:
- GetMethod
- Put
- SpawnInstance
Added function to IWbemServices:
- ExecMethod

Added GetMethod, Put, SpawnInstance, and ExecMethod functions

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/bsd/ExtAttr.java
contrib/platform/src/com/sun/jna/platform/bsd/ExtAttrUtil.java

This is a JNA wrapper for the libc xattr functions on BSD platforms (similar to the native bindings already available for Linux and macOS in the platform jar).
The primary motivation for this contribution is `UnixUserDefinedFileAttributeView.list()` not working in the OpenJDK FreeBSD port:
https://github.com/battleblow/jdk17u/commit/05dca178dc6c3e9390684aa82ed2484c245c43aa#r125181377
NOTE:
This code is tested on production on FreeBSD, but we don't have automated test cases because the `sys/extattr.h` native functions are only available on BSD platforms, and so automated tests on Linux won't work.

Wrap BSD <sys/extattr.h> system calls

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Winspool.java

Adds the ability to call `SetJob` and `SetPrinter` for advanced printer and job control.
Quoting MSN:
> ### SetJob
> The `SetJob` function pauses, resumes, cancels, or restarts a print job on a specified printer. You can also use the `SetJob` function to set print job parameters, such as the **print job priority** and the **document name.**
> 
> You can use the SetJob function to give a command to a print job, or to set print job parameters, or to do both in the same call. The value of the `Command` parameter does not affect how the function uses the `Level` and `pJob` parameters. Also, you can use SetJob with `JOB_INFO_3` to link together a set of print jobs. See Remarks for more information.
> 
> ### SetPrinter
> The `SetPrinter` function sets the data for a specified printer or sets …

Add SetJob, SetPrinter to Winspool

---

contrib/platform/src/com/sun/jna/platform/win32/WinNT.java

Updates documentation for the `LOGICAL_PROCESSOR_RELATIONSHIP` enum.
See https://learn.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-logical_processor_relationship and https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlogicalprocessorinformationex
(Finally) Fixes #1324 
As this is a javadoc-only change, I don't think a change log entry is needed.

Update docs for WinNT#LOGICAL_PROCESSOR_RELATIONSHIP

---

src/com/sun/jna/CallbackReference.java
src/com/sun/jna/DefaultTypeMapper.java
src/com/sun/jna/ELFAnalyser.java
src/com/sun/jna/Klass.java
src/com/sun/jna/Library.java
src/com/sun/jna/Memory.java
src/com/sun/jna/Native.java
src/com/sun/jna/NativeLibrary.java
src/com/sun/jna/NativeMappedConverter.java
src/com/sun/jna/Pointer.java
src/com/sun/jna/StringArray.java
src/com/sun/jna/Structure.java
src/com/sun/jna/Union.java
src/com/sun/jna/VarArgsChecker.java
src/com/sun/jna/WeakMemoryHolder.java
src/com/sun/jna/internal/Cleaner.java
src/com/sun/jna/internal/ReflectionUtils.java
test/com/sun/jna/CallbacksTest.java
test/com/sun/jna/DirectArgumentsWrappersMarshalTest.java
test/com/sun/jna/DirectTest.java
test/com/sun/jna/ELFAnalyserTest.java
test/com/sun/jna/JNALoadTest.java
test/com/sun/jna/LastErrorTest.java
test/com/sun/jna/MemoryTest.java
test/com/sun/jna/NativeLibraryTest.java
test/com/sun/jna/NativeTest.java
test/com/sun/jna/StructureFieldOrderInspector.java
test/com/sun/jna/StructureFieldOrderInspectorTest.java
test/com/sun/jna/StructureTest.java
test/com/sun/jna/WebStartTest.java

Used IDE cleanup tool with manual reverting of the anonymous inner class fixes to apply the following (each in a separate commit for ease of review or if you only want a portion of the changes):
- Diamond Operators
- Try-with-resources
- Try-multi-catch
- Constants in preference to system properties

Use JDK7 and JDK8 Code Features

---

.github/dependabot.yml
.github/workflows/ci.yaml

Fixes https://github.com/java-native-access/jna/issues/1566.
This PR adds Dependabot to monitor JNA's GitHub Actions. It also bumps `actions/checkout@v3` to `v4`, the sort of thing Dependabot would otherwise do itself (see [the PR on my fork](https://github.com/pnacht/jna/pull/1)).
Dependabot is configured to use grouped updates. So if more than one Action releases a new version, you'll only receive a single PR updating all Actions instead of one PR per Action. This admittedly isn't too likely to happen currently, seeing as the project only uses two Actions, but can prove far more useful should the project add more workflows with more Actions in the future.

Add dependabot to monitor GHA

---

src/com/sun/jna/Function.java
src/com/sun/jna/NativeLibrary.java

Integrate reported quality issues

---

CHANGES.md
src/com/sun/jna/ELFAnalyser.java

The ELFAnalyser failed to analyse the java binary on Java 8 for armv7 synology NAS systems (DS115j, ...). The binary did not contain an ELF section header table, which caused an IndexOutOfBoundsException.
Closes: #1579

Handle ELF binaries without section header table

---

.github/workflows/ci.yaml
.github/workflows/native-libraries-macOS.yaml
contrib/platform/test/com/sun/jna/platform/mac/IOKitTest.java

Improve Testing / native libarary building for darwin/mac OS

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java

Adds `IsProcessorFeaturePresent` from Kernel32.
- Docs: https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent
- Sample working code: https://github.com/oshi/oshi/blob/44287a3ec860f6a9d79ac97e728c7e3a71042189/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java#L192-L194
- Sample working code test run: https://github.com/oshi/oshi/actions/runs/8219539169/job/22477628581#step:4:408

Add IsProcessorFeaturePresent to c.s.j.p.win32.Kernel32

---

appveyor.yml

Attempting fix from https://help.appveyor.com/discussions/problems/2229-v140-not-found-on-vs2105rc

Fix Appveyor build

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/unix/X11.java

This PR adds the following X11 calls:
- XMoveWindow
- XResizeWindow
- XMoveResizeWindow
- XRaiseWindow
- XLowerWindow

feat: X11 window move, resize, raise and lower calls

---

CHANGES.md
build.xml

Add "linux-riscv64" entry to OSGI Bundle-NativeCode header in MANIFEST.MF

---

CHANGES.md
src/com/sun/jna/Structure.java

Fixes java-native-access/jna#1625 issue by caching the field list (``fieldList``) and validation state (``validationMap``) in addition to the existing ``layoutInfo`` and ``fieldOrder`` caches.
Caching this additional state provides substantial performance improvements.

Improve ``Structure`` (subclass) construction performance.

---

build.xml
common.xml
contrib/platform/src/com/sun/jna/platform/unix/solaris/Kstat2.java

Fix javadoc

---

.github/workflows/ci.yaml

👋 as java 23 already ga, update to support it.

ci: support java 23 (as java 23 already ga)

---

CHANGES.md
contrib/platform/src/com/sun/jna/platform/win32/WinNT.java
contrib/platform/src/com/sun/jna/platform/win32/WinUser.java
contrib/platform/test/com/sun/jna/platform/win32/User32Test.java

Add some missing power event constants, types, and functions.

Add power event constants, types, and functions

---

.github/workflows/ci.yaml
build.xml
contrib/platform/build.xml

- enable running CI/CD matrix on JDK24 (dropping JDK23 for this)
- adjust build script to set parameters so that unittests run without warnings from native access

Prepare build for JDK24+

---

build.xml
src/com/sun/jna/overview.html

Document changes required for running JNA on JDK24+

---

native/libffi/src/aarch64/sysv.S

This fixes the build failures caused by changes in the latest version of clang. See this related fix in libffi:
[Move cfi_startproc after CNAME(label) in aarch64/sysv.S](https://github.com/libffi/libffi/pull/857)

Fix native build error on Xcode 16.3 / Apple Clang 17

---

CHANGES.md
src/com/sun/jna/Structure.java

I used essentially the same pattern than `validateFields` uses.

Avoid threading issues in sortFields (#1686)
