README.md
Added "FileBot" to "Projects Using JNA"
=> Added "FileBot" to "Projects Using JNA"

contrib/platform/src/com/sun/jna/platform/win32/Advapi32Util.java
=> fixed #460

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/WinDef.java, contrib/platform/src/com/sun/jna/platform/win32/WinNT.java, contrib/platform/test/com/sun/jna/platform/win32/Kernel32DiskManagementFunctionsTest.java, contrib/platform/test/com/sun/jna/platform/win32/WinDefTypesTest.java, contrib/platform/test/com/sun/jna/platform/win32/WinNTTypesTest.java, src/com/sun/jna/IntegerType.java, test/com/sun/jna/IntegerTypeTest.java
Feels more natural for these types as well as laying the groundwork for more such implementations for derived class - e.g., LCID, ATOM, etc...
=> Implemented Comparable interface for many of the base types in WinDef

native/callback.c, native/dispatch.c, native/testlib.c, src/com/sun/jna/Native.java, test/com/sun/jna/DirectTest.java, test/com/sun/jna/GCWaits.java, test/com/sun/jna/JNALoadTest.java, test/com/sun/jna/MemoryTest.java, test/com/sun/jna/Paths.java, test/com/sun/jna/PerformanceTest.java
Addresses functionality missed in previous CC PR.
=> Add alternate call convention handling to callbacks

contrib/platform/build.xml, contrib/platform/test/com/sun/jna/platform/win32/Shell32Test.java
Also avoid tweaking the desktop layout so much during the test.
=> Avoid overwriting test results from different platforms

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java, contrib/platform/test/com/sun/jna/platform/win32/Kernel32Test.java
~~Junit test depends on resolution of #546~~
=> Add GetSystemTimes() to Kernel32

.gitignore, CHANGES.md, native/build.xml, native/pom.xml, parent/build-base.xml, parent/build-compile.xml, parent/pom.xml
based on PR #582 from @lgoldstein (#582) and PR #596.
removed unused ignores, replaced tabs with spaces and squashes other commits.
=> Mavenize the build process - Phase 1: building the native code via Maven

contrib/monitordemo/.classpath, contrib/monitordemo/.project, contrib/monitordemo/build.xml, contrib/msoffice/.classpath, contrib/msoffice/build.xml, contrib/msoffice/src/com/sun/jna/platform/win32/COM/util/office/MSOfficeWordDemo.java, contrib/native_window_msg/.classpath, contrib/native_window_msg/build.xml, contrib/native_window_msg/src/com/sun/jna/platform/win32/Win32WindowDemo.java, contrib/w32printing/.classpath, contrib/w32printing/build.xml
correct compile errors, fixed eclipse project files and created build.xml for contrib projects
=> fixed compile errors

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java, contrib/platform/test/com/sun/jna/platform/win32/COM/ITypeInfoTest.java, contrib/platform/test/com/sun/jna/platform/win32/COM/ShellApplicationWindowsTest.java, contrib/platform/test/com/sun/jna/platform/win32/COM/util/ConvertTest.java, contrib/platform/test/com/sun/jna/platform/win32/COM/util/IDispatchTest.java
This is a followup to pull #625. The points that were raised by @dblock and @lgoldstein were addressed.
=> Adjust changelog entry and incorrect assert usage in tests.

LICENSE
As a follow up on my initial issue #643, here is a wording modification proposal.
=> Clarify the dual license wording

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/COM/COMLateBindingObject.java
=> Use correct object for getAutomationProperty when IDispatch is passed in

.github/ISSUE_TEMPLATE.md
=> Add issue template to replace "marker issue"

build.xml
feel free to update the year once enough copyrightable changes were done
=> fix reproducible builds

CHANGES.md, src/com/sun/jna/Native.java, test/com/sun/jna/NativeTest.java
=> Check native version before attempting to call into native code

CHANGES.md, build.xml, www/ReleasingJNA.md
- A new dist artifact was added: jna.aar (the AAR itself)
- Maven tasks were updated to publish *.aar
(Modified + Tested: install, deploy, stage)
The generated aar was tested using Android Studio 2.2.3
=> Build android archive (AAR)

contrib/platform/test/com/sun/jna/platform/win32/DdemlUtilTest.java
Hi,
There is a minor typo in DdemlUtilTest "quietly" is misspelled "quitely".
=> Typo in DdemlUtilTest (quitely -> quietly)

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/Ole32.java, contrib/platform/src/com/sun/jna/platform/win32/OleAuto.java, contrib/platform/src/com/sun/jna/platform/win32/WinNT.java, contrib/platform/test/com/sun/jna/platform/win32/Ole32Test.java, contrib/platform/test/com/sun/jna/platform/win32/OleAutoTest.java
This is a refreshed version of #282. 
Unittests were added and the changeset was adapted to the changes in the JNA structure.
Closes: #282
=> Interfaces from Ole32 and OleAuto

contrib/platform/src/com/sun/jna/platform/win32/Ddeml.java
Hi,
Here are some improvements to the DDE javadoc, mostly links to facilitate the navigation.
=> DDE javadoc improvements

www/FrequentlyAskedQuestions.md
=> Android documentation

www/FrequentlyAskedQuestions.md
=> Add FAQ for Windows API function naming

contrib/platform/src/com/sun/jna/platform/win32/COM/EnumVariant.java, contrib/platform/src/com/sun/jna/platform/win32/COM/IComEnumVariantIterator.java, contrib/platform/src/com/sun/jna/platform/win32/COM/IEnumVariant.java, contrib/platform/test/com/sun/jna/platform/win32/COM/EnumVariantTest.java
=> Add support for IEnumVariant

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/Winspool.java, contrib/platform/test/com/sun/jna/platform/win32/WinspoolTest.java
=> Declare structure members of LPPRINTER_DEFAULTS as public

CHANGES.md, src/com/sun/jna/ELFAnalyser.java
=> Correctly close RandomAccessFile in ELFAnalyser#runDetection

CHANGES.md, contrib/platform/src/com/sun/jna/platform/win32/COM/util/ProxyObject.java, contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectFactory_Test.java, contrib/platform/test/com/sun/jna/platform/win32/COM/util/ProxyObjectObjectFactory_Test.java
=> NullPointerException can be caused by calling ProxyObject#dispose multiple times

.github/ISSUE_TEMPLATE.md, README.md
=> Add description for the primary artifacts and update issue reporting instructions

contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java, src/com/sun/jna/Version.java
=> Adjust licensing to declared project license (followup for PR #711)

src/com/sun/jna/overview.html
Addresses issue #105. I have not verified that the document still renders correctly.
=> Clarify the use of Buffers

CHANGES.md
This fixes a broken link the changelog and updates it to HTTPS.
=> Fix dead link in CHANGES.md

contrib/platform/build.xml
=> Add com.sun.jna.platform.linux to OSGi bundle

src/com/sun/jna/Memory.java, src/com/sun/jna/Pointer.java
will try to contribute in my spare time (this is a demo PR)
=> Hello world, fix minor sonar issues

www/DirectMapping.md
Fix syntax highlighting for java code block
=> Fix syntax highlighting for java code block

contrib/platform/src/com/sun/jna/platform/mac/CoreFoundation.java, contrib/platform/src/com/sun/jna/platform/mac/IOKit.java, contrib/platform/src/com/sun/jna/platform/win32/Kernel32.java
Found a few stray javadoc problems I left in #1131 and another one from #1124 so I can pretend this is not all my fault. :)
=> Javadoc cleanup

contrib/platform/build.xml
=> Include Win32 COM utils in OSGI bundle

contrib/platform/src/com/sun/jna/platform/win32/PsapiUtil.java, contrib/platform/test/com/sun/jna/platform/win32/PsapiUtilTest.java
Signed-off-by: Torbjörn Svensson <azoff@svenskalinuxforeningen.se>
=> Fixed typo in email address

contrib/dnddemo/package.html, contrib/platform/src/com/sun/jna/platform/dnd/package.html, contrib/platform/src/com/sun/jna/platform/linux/package.html, contrib/platform/src/com/sun/jna/platform/mac/package.html, contrib/platform/src/com/sun/jna/platform/package.html, contrib/platform/src/com/sun/jna/platform/unix/package.html, contrib/platform/src/com/sun/jna/platform/unix/solaris/package.html, contrib/platform/src/com/sun/jna/platform/win32/COM/package.html, contrib/platform/src/com/sun/jna/platform/win32/COM/tlb/imp/package.html, contrib/platform/src/com/sun/jna/platform/win32/COM/tlb/package.html, contrib/platform/src/com/sun/jna/platform/win32/COM/util/annotation/package.html, contrib/platform/src/com/sun/jna/platform/win32/COM/util/package.html, contrib/platform/src/com/sun/jna/platform/win32/package.html, contrib/platform/src/com/sun/jna/platform/wince/package.html, src/com/sun/jna/internal/package.html, src/com/sun/jna/ptr/package.html, src/com/sun/jna/win32/package.html
Added license headers to existing package.html files. 
Completed "Provides..." stub on files with incomplete descriptions.  
Added package.html files when they were missed in a package.
=> Add/complete missing package.html files and update license headers

contrib/platform/src/com/sun/jna/platform/win32/COM/util/Convert.java, contrib/platform/src/com/sun/jna/platform/win32/Variant.java
Reduced the number of Variant.getVarType and Variant.getValue calls while reading an Variant.
=> Minor improvements to code related to Variants

.github/workflows/ci.yaml, src/com/sun/jna/CallbackReference.java
See #1282. 
Currently set to run on push to master, pull requests, and by request (click the button). Can fine tune this.
=> Github actions for macOS and Linux

README.md
Update some broken links and old information in projects, remove a few projects that seem to no longer exist, add JNAJack.
=> Update README Projects using JNA.

www/FrequentlyAskedQuestions.md
Consolidating discussion from the mailing list into the FAQ.
=> Add JPMS artifact details to FAQ

LICENSE, README.md
Closes #1307 
@hyandell: does this address your concerns? 
@twall: I included your email for commercial requests, ok with this? use different email?
@dbwiddis, @matthiasblaesing: CR please
=> Clarified dual license and added SPDX-License-Identifier.

contrib/platform/test/com/sun/jna/platform/mac/CoreFoundationTest.java
=> more assertions for CFDictionaryRef.ByReference and CFStringRef.ByRererence

build.xml
=> support for Eclipse on Windows on Arm64 platform

native/callback.c
=> Fix free_callback JNI weak reference leak

contrib/platform/src/com/sun/jna/platform/win32/GDI32.java
=> Fixed typo in GDI32.java

build.xml
=> Fix missing javadoc file resoures/fonts/dejavu.css

LICENSE
=> Update SPDX identifiers to match pom and license headers in files
